import { NextResponse } from "next/server";
import { isSuperAdmin, requireSession } from "@/lib/auth";
import { getPrisma } from "@/lib/prisma";
import { getTenantCrmConfiguration } from "@/lib/vertical-template";

async function authorize(){const session=await requireSession();if(!isSuperAdmin(session))throw new Response("Solo SUPER_ADMIN puede administrar plantillas verticales",{status:403})}
export async function GET(_request:Request,{params}:{params:Promise<{tenantId:string}>}){try{await authorize();const{tenantId}=await params;const assignment=await getTenantCrmConfiguration(tenantId),maxUsers=await getPrisma().tenantLimitOverride.findFirst({where:{tenantId,definition:{code:"max-users"}},include:{definition:true}}),activeUsers=await getPrisma().user.count({where:{tenantId,status:"ACTIVE"}});return NextResponse.json({assignment,maxUsers:Number(maxUsers?.value??0),activeUsers})}catch(error){if(error instanceof Response)return NextResponse.json({message:(await error.text())||"Acceso denegado"},{status:error.status});return NextResponse.json({message:"No se pudo consultar la plantilla."},{status:400})}}
export async function PATCH(request:Request,{params}:{params:Promise<{tenantId:string}>}){try{await authorize();const{tenantId}=await params,body=await request.json() as {featureId?:string;active?:boolean;maxUsers?:number;verticalTemplateId?:string|null};
  if("verticalTemplateId" in body){await getPrisma().$transaction(async tx=>{await tx.tenantCrmFeature.deleteMany({where:{tenantId}});await tx.tenantVerticalTemplate.deleteMany({where:{tenantId}});if(body.verticalTemplateId){const template=await tx.verticalTemplate.findFirst({where:{id:body.verticalTemplateId,active:true},include:{features:true}});if(!template)throw new Response("Plantilla vertical no válida",{status:400});await tx.tenantVerticalTemplate.create({data:{tenantId,verticalTemplateId:template.id,active:true}});await tx.tenantCrmFeature.createMany({data:template.features.map(feature=>({tenantId,featureId:feature.id,active:feature.defaultActive}))})}})}
  else if(body.featureId){const feature=await getPrisma().verticalTemplateFeature.findFirst({where:{id:body.featureId,verticalTemplate:{tenants:{some:{tenantId,active:true}}}}});if(!feature)throw new Response("Función fuera de la plantilla del tenant",{status:403});await getPrisma().tenantCrmFeature.upsert({where:{tenantId_featureId:{tenantId,featureId:feature.id}},update:{active:Boolean(body.active)},create:{tenantId,featureId:feature.id,active:Boolean(body.active)}})}
  else if(body.maxUsers!==undefined){const value=Math.trunc(Number(body.maxUsers));if(!Number.isFinite(value)||value<1)throw new Response("El límite debe ser mayor que cero",{status:400});const definition=await getPrisma().limitDefinition.findUniqueOrThrow({where:{code:"max-users"}});await getPrisma().tenantLimitOverride.upsert({where:{tenantId_limitId:{tenantId,limitId:definition.id}},update:{value},create:{tenantId,limitId:definition.id,value}})}
  else return NextResponse.json({message:"No hay cambios para guardar."},{status:400});return GET(request,{params:Promise.resolve({tenantId})})
 }catch(error){if(error instanceof Response)return NextResponse.json({message:(await error.text())||"Acceso denegado"},{status:error.status});console.error("No se pudo actualizar plantilla",error);return NextResponse.json({message:"No se pudo guardar la configuración."},{status:400})}}
