"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type View="sales"|"customers";
type Meta={products:Array<{id:string;name:string}>;commercialPlans:Array<{id:string;name:string;productId:string}>;activeFeatures:string[]};
type PageData<T>={items:T[];total:number;page:number;pageSize:number;totalPages:number;facets?:{historicalAdvisors:string[]};summary?:{customers:number;sales:number;approvedSales:number;monthSales:number}};
type SaleRow={id:string;saleDate:string;status:string;transactionType:string;customerNameSnapshot:string;customerDocumentSnapshot:string|null;productNameSnapshot:string;planNameSnapshot:string|null;msisdn:string|null;sec:string|null;sot:string|null;historicalAdvisorName:string|null;historicalSupervisorName:string|null;customer:{phone:string};agent:{id:string;name:string}|null};
type CustomerRow={id:string;name:string;document:string|null;phone:string;email:string|null;status:string;createdAt:string;ownerUser:{id:string;name:string}|null;_count:{sales:number};lastSale:{saleDate:string;productNameSnapshot:string;planNameSnapshot:string|null;status:string}|null};
type SaleDetail=SaleRow&{customer:{phone:string;email?:string|null;address?:string|null;city?:string|null};commercialPlan?:{name:string}|null;product?:{name:string};salesChannel?:string|null;pointOfSale?:string|null;source?:string|null;notes?:string|null;fixedChargeSnapshot?:string|null;saleAmount?:string|null;historicalSupervisorName:string|null;supervisor?:{name:string}|null;statusHistory:Array<{id:string;newStatus:string;previousStatus:string|null;changedAt:string;reason:string|null;changedByUser:{name:string}}>};
type CustomerDetail=CustomerRow&{createdAt:string;city:string|null;address:string|null;sales:Array<{id:string;saleDate:string;productNameSnapshot:string;planNameSnapshot:string|null;transactionType:string;status:string;sec:string|null;sot:string|null;msisdn:string|null;historicalAdvisorName:string|null}>};
const navigation=[{id:"leads",label:"Leads"},{id:"customers",label:"Clientes"},{id:"sales",label:"Ventas"},{id:"follow-ups",label:"Seguimientos"},{id:"products",label:"Productos"},{id:"commercial-plans",label:"Planes comerciales"},{id:"commissions",label:"Comisiones"},{id:"reconciliation",label:"Liquidaciones"},{id:"finance",label:"Finanzas"},{id:"payroll",label:"Pago de Personal"},{id:"commercial-management",label:"Gestión Comercial"},{id:"promoter-space",label:"Espacio Promotor"}];
const operations=["PORTABILIDAD","ALTA_NUEVA","PORTABILIDAD_POSTPAGO","ALTA_NUEVA_POSTPAGO","MIGRACION","PREPAGO","RENOVACION","LINEA_FIJA","INTERNET_FIJO","OTRO"];
const statuses=["REGISTRADA","EN_VALIDACION","APROBADA","ACTIVADA","RECHAZADA","CANCELADA"];
const initialFilters={search:"",dateFrom:"",dateTo:"",productId:"",commercialPlanId:"",transactionType:"",status:"",historicalAdvisorName:""};

export function CrmOperationalWorkspace({view,administrativeTenant}:{view:View;administrativeTenant?:string|null}){
  const[meta,setMeta]=useState<Meta>({products:[],commercialPlans:[],activeFeatures:[]});
  const[data,setData]=useState<PageData<SaleRow|CustomerRow>>({items:[],total:0,page:1,pageSize:25,totalPages:1});
  const[filters,setFilters]=useState(initialFilters),[applied,setApplied]=useState(initialFilters),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const[selectedSale,setSelectedSale]=useState<SaleDetail|null>(null),[selectedCustomer,setSelectedCustomer]=useState<CustomerDetail|null>(null),[detailLoading,setDetailLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const query=new URLSearchParams({page:String(page),pageSize:"25"});Object.entries(applied).forEach(([key,value])=>{if(value)query.set(key,value)});const[response,metaResponse]=await Promise.all([fetch(`/api/crm/${view}?${query}`),fetch("/api/crm/operational-meta")]);const[result,metaResult]=await Promise.all([response.json(),metaResponse.json()]);if(response.ok){setData(result);setMessage("")}else setMessage(result.message);if(metaResponse.ok)setMeta(metaResult);setLoading(false)},[view,page,applied]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  function apply(event:React.FormEvent){event.preventDefault();setPage(1);setApplied(filters)}
  function clear(){setFilters(initialFilters);setApplied(initialFilters);setPage(1)}
  async function openDetail(id:string){setDetailLoading(true);const response=await fetch(`/api/crm/${view}/${id}`),result=await response.json();if(response.ok){if(view==="sales")setSelectedSale(result.item);else setSelectedCustomer(result.item)}else setMessage(result.message);setDetailLoading(false)}
  const plans=meta.commercialPlans.filter(item=>!filters.productId||item.productId===filters.productId);
  return <>{administrativeTenant&&<div className="admin-context"><span>◎</span><div><small>EMPRESA</small><strong>{administrativeTenant}</strong></div><div><small>MODO</small><strong>Administración</strong></div></div>}
    <section className="page-title crm-title"><div><span className="eyebrow">CRM · DATOS REALES</span><h1>{view==="sales"?"Ventas":"Clientes"}</h1><p>{view==="sales"?"Operaciones comerciales registradas en PostgreSQL.":"Vista comercial consolidada con el historial real de ventas."}</p></div><div className="operational-total"><strong>{data.total.toLocaleString("es-PE")}</strong><span>{view==="sales"?"ventas encontradas":"clientes encontrados"}</span></div></section>
    <nav className="crm-tabs">{navigation.filter(item=>meta.activeFeatures.includes(item.id)).map(item=><Link className={item.id===view?"selected":""} key={item.id} href={`/crm/${item.id}`}>{item.label}</Link>)}</nav>
    {view==="customers"&&data.summary&&<section className="customer-kpis"><CustomerKpi icon="◎" tone="violet" label="Clientes totales" value={data.summary.customers}/><CustomerKpi icon="▥" tone="blue" label="Ventas registradas" value={data.summary.sales}/><CustomerKpi icon="✓" tone="green" label="Ventas aprobadas" value={data.summary.approvedSales}/><CustomerKpi icon="◷" tone="amber" label="Ventas del mes" value={data.summary.monthSales}/></section>}
    <form className={`card operational-filters ${view}`} onSubmit={apply}><label className="search-field"><span>Buscar</span><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder={view==="sales"?"Cliente, documento, teléfono, MSISDN, SEC o SOT":"Nombre, documento, teléfono o email"}/></label>{view==="sales"&&<><label>Desde<input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/></label><label>Hasta<input type="date" value={filters.dateTo} onChange={e=>setFilters({...filters,dateTo:e.target.value})}/></label><label>Producto<select value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value,commercialPlanId:""})}><option value="">Todos</option>{meta.products.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Plan<select value={filters.commercialPlanId} onChange={e=>setFilters({...filters,commercialPlanId:e.target.value})}><option value="">Todos</option>{plans.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Operación<select value={filters.transactionType} onChange={e=>setFilters({...filters,transactionType:e.target.value})}><option value="">Todas</option>{operations.map(item=><option key={item}>{item}</option>)}</select></label><label>Estado<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><label>Asesor histórico<select value={filters.historicalAdvisorName} onChange={e=>setFilters({...filters,historicalAdvisorName:e.target.value})}><option value="">Todos</option>{data.facets?.historicalAdvisors.map(item=><option key={item}>{item}</option>)}</select></label></>}<div className="filter-actions"><button className="secondary" type="button" onClick={clear}>Limpiar</button><button className="primary">Aplicar filtros</button></div></form>
    {message&&<p className="form-error">{message}</p>}
    <section className="card operational-table-card">{loading?<div className="empty-core">Consultando datos reales…</div>:data.items.length===0?<div className="operational-empty"><strong>Sin coincidencias</strong><span>No existen registros para los filtros seleccionados.</span></div>:view==="sales"?<SalesTable items={data.items as SaleRow[]} open={id=>void openDetail(id)}/>:<CustomersTable items={data.items as CustomerRow[]} open={id=>void openDetail(id)}/>}<Pagination page={data.page} pages={data.totalPages} total={data.total} pageSize={data.pageSize} setPage={setPage}/></section>
    {detailLoading&&<div className="detail-backdrop"><div className="detail-panel loading">Consultando detalle…</div></div>}
    {selectedSale&&<SaleDrawer item={selectedSale} close={()=>setSelectedSale(null)}/>} {selectedCustomer&&<CustomerDrawer item={selectedCustomer} close={()=>setSelectedCustomer(null)}/>} </>;
}

function SalesTable({items,open}:{items:SaleRow[];open:(id:string)=>void}){return <div className="table-scroll"><table className="operational-table sales-table"><thead><tr><th>Fecha</th><th>DNI</th><th>Cliente</th><th>Teléfono</th><th>Producto / plan</th><th>Operación</th><th>Estado</th><th>Asesor</th><th>SEC / SOT</th><th>Acción</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{date(item.saleDate)}</td><td>{item.customerDocumentSnapshot||"—"}</td><td><strong>{item.customerNameSnapshot}</strong></td><td>{item.msisdn||item.customer.phone||"—"}</td><td><strong>{item.productNameSnapshot}</strong>{item.planNameSnapshot&&<small>{item.planNameSnapshot}</small>}</td><td>{friendlyOperation(item.transactionType)}</td><td><Status value={item.status}/></td><td><strong>{item.historicalAdvisorName||item.agent?.name||"—"}</strong></td><td><strong>{item.sec?`SEC: ${item.sec}`:"—"}</strong>{item.sot&&<small>SOT: {item.sot}</small>}</td><td><button className="secondary" onClick={()=>open(item.id)}>Ver detalle</button></td></tr>)}</tbody></table></div>}
function CustomersTable({items,open}:{items:CustomerRow[];open:(id:string)=>void}){return <div className="table-scroll"><table className="operational-table customers-table"><thead><tr><th>DNI</th><th>Cliente</th><th>Teléfono</th><th>Ventas</th><th>Última venta</th><th>Último producto / plan</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.document||"—"}</td><td><strong>{item.name}</strong></td><td>{item.phone||"—"}</td><td><button className="sale-count" title="Ver historial de ventas" onClick={()=>open(item.id)}>{item._count.sales}</button></td><td>{item.lastSale?<strong>{date(item.lastSale.saleDate)}</strong>:"—"}</td><td><strong>{item.lastSale?.productNameSnapshot||"—"}</strong>{item.lastSale?.planNameSnapshot&&<small>{item.lastSale.planNameSnapshot}</small>}</td><td>{item.lastSale?<Status value={item.lastSale.status}/>:"—"}</td><td><button className="secondary" onClick={()=>open(item.id)}>Ver ficha</button></td></tr>)}</tbody></table></div>}
function CustomerKpi({icon,tone,label,value}:{icon:string;tone:"violet"|"blue"|"green"|"amber";label:string;value:number}){return <article className={tone}><span className="customer-kpi-icon" aria-hidden="true">{icon}</span><div><small>{label}</small><strong>{value.toLocaleString("es-PE")}</strong></div></article>}
function Pagination({page,pages,total,pageSize,setPage}:{page:number;pages:number;total:number;pageSize:number;setPage:(value:number)=>void}){if(!total)return null;return <div className="operational-pagination"><span>Mostrando {(page-1)*pageSize+1}–{Math.min(page*pageSize,total)} de {total}</span><div><button className="secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><strong>Página {page} de {pages}</strong><button className="secondary" disabled={page>=pages} onClick={()=>setPage(page+1)}>Siguiente</button></div></div>}
function SaleDrawer({item,close}:{item:SaleDetail;close:()=>void}){return <div className="detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="detail-panel"><header><div><span>DETALLE DE VENTA</span><h2>{item.customerNameSnapshot}</h2><p>{item.id}</p></div><button onClick={close}>×</button></header><DetailSection title="Datos de venta" values={[["Fecha",date(item.saleDate)],["Estado",label(item.status)],["Operación",label(item.transactionType)],["Canal",item.salesChannel],["Punto de venta",item.pointOfSale]]}/><DetailSection title="Cliente" values={[["Nombre",item.customerNameSnapshot],["Documento",item.customerDocumentSnapshot],["Teléfono",item.customer.phone],["MSISDN",item.msisdn]]}/><DetailSection title="Producto" values={[["Producto",item.productNameSnapshot],["Plan",item.planNameSnapshot],["Cargo fijo snapshot",money(item.fixedChargeSnapshot)],["Monto de venta",money(item.saleAmount)]]}/><DetailSection title="Trazabilidad" values={[["SEC",item.sec],["SOT",item.sot],["Origen",item.source]]}/><DetailSection title="Gestión comercial" values={[["Asesor histórico",item.historicalAdvisorName],["Supervisor histórico",item.historicalSupervisorName],["Usuario actual",item.agent?.name],["Supervisor actual",item.supervisor?.name]]}/>{item.notes&&<DetailSection title="Observaciones" values={[["Notas",item.notes]]}/>}<section className="detail-history"><h3>Historial de estados</h3>{item.statusHistory.length?item.statusHistory.map(row=><div key={row.id}><Status value={row.newStatus}/><span><strong>{row.changedByUser.name}</strong><small>{new Date(row.changedAt).toLocaleString("es-PE")}{row.reason?` · ${row.reason}`:""}</small></span></div>):<p>Sin cambios de estado registrados.</p>}</section></aside></div>}
function CustomerDrawer({item,close}:{item:CustomerDetail;close:()=>void}){const sales=item.sales,products=[...new Set(sales.map(s=>s.productNameSnapshot))],plans=[...new Set(sales.flatMap(s=>s.planNameSnapshot?[s.planNameSnapshot]:[]))];return <div className="detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="detail-panel customer-detail"><header><div><span>FICHA COMERCIAL</span><h2>{item.name}</h2><p>{item.document||"Sin documento"}</p></div><button onClick={close}>×</button></header><DetailSection title="Datos generales" values={[["Nombre",item.name],["Documento",item.document],["Teléfono",item.phone],["Email",item.email],["Creado",date(item.createdAt)],["Responsable actual",item.ownerUser?.name]]}/><section className="customer-commercial-summary"><article><small>Total ventas</small><strong>{sales.length}</strong></article><article><small>Primera venta</small><strong>{sales.length?date(sales[sales.length-1].saleDate):"—"}</strong></article><article><small>Última venta</small><strong>{sales.length?date(sales[0].saleDate):"—"}</strong></article></section><DetailSection title="Productos y planes adquiridos" values={[["Productos",products.join(", ")||null],["Planes",plans.join(", ")||null]]}/><section className="customer-sales-history"><h3>Historial de ventas</h3>{sales.length?<div className="table-scroll"><table className="operational-table"><thead><tr><th>Fecha</th><th>Producto / plan</th><th>Operación</th><th>Estado</th><th>SEC / SOT / MSISDN</th><th>Asesor</th></tr></thead><tbody>{sales.map(sale=><tr key={sale.id}><td>{date(sale.saleDate)}</td><td><strong>{sale.productNameSnapshot}</strong><small>{sale.planNameSnapshot||"Sin plan"}</small></td><td>{label(sale.transactionType)}</td><td><Status value={sale.status}/></td><td><strong>{sale.sec||"—"} · {sale.sot||"—"}</strong><small>{sale.msisdn||"Sin MSISDN"}</small></td><td>{sale.historicalAdvisorName||"Sin asesor histórico"}</td></tr>)}</tbody></table></div>:<p>Este cliente no tiene ventas registradas.</p>}</section></aside></div>}
function DetailSection({title,values}:{title:string;values:Array<[string,string|null|undefined]>}){const visible=values.filter(([,value])=>value);return <section className="detail-section"><h3>{title}</h3><div>{visible.map(([key,value])=><article key={key}><small>{key}</small><strong>{value}</strong></article>)}</div></section>}
function Status({value}:{value:string}){return <span className={`operational-status ${value.toLowerCase()}`}>{label(value)}</span>}
function date(value:string){return new Date(value).toLocaleDateString("es-PE")}
function label(value:string){return value.replaceAll("_"," ")}
function friendlyOperation(value:string){return label(value).toLocaleLowerCase("es-PE").replace(/^./,letter=>letter.toUpperCase())}
function money(value?:string|null){return value?`S/ ${Number(value).toFixed(2)}`:null}
