"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type View = "leads" | "customers" | "sales" | "follow-ups" | "products" | "commercial-plans";
type Meta = { stages: Array<{id:string;name:string;color?:string}>; users:Array<{id:string;name:string;role:{code:string}}> ; products:Array<{id:string;name:string}>; commercialPlans:Array<{id:string;name:string;productId:string}>; leads:Array<{id:string;name:string}>; customers:Array<{id:string;name:string}>; role:string; activeFeatures:string[] };
type RecordItem = Record<string, unknown> & { id:string; name?:string; status?:string; phone?:string; email?:string; code?:string; category?:string; origin?:string; pipelineStageId?:string; assignedUserId?:string; ownerUserId?:string; scheduledAt?:string; saleDate?:string; transactionType?:string; customerNameSnapshot?:string; customerDocumentSnapshot?:string; productNameSnapshot?:string; planNameSnapshot?:string; msisdn?:string; sec?:string; sot?:string; salesChannel?:string; pointOfSale?:string; notes?:string; type?:string; productId?:string; price?:string; fixedCharge?:string; validFrom?:string; validTo?:string; pipelineStage?:{name:string;color?:string}; assignedUser?:{name:string}; ownerUser?:{name:string}; agent?:{name:string}; supervisor?:{name:string}; product?:{name:string}; lead?:{name:string}; customer?:{name:string}; statusHistory?:Array<{id:string;previousStatus?:string;newStatus:string;changedAt:string;reason?:string;changedByUser:{name:string}}> };
const views: Array<{id:View;label:string}> = [{id:"leads",label:"Leads"},{id:"customers",label:"Clientes"},{id:"sales",label:"Ventas"},{id:"follow-ups",label:"Seguimientos"},{id:"products",label:"Productos"},{id:"commercial-plans",label:"Planes comerciales"}];
const titles:Record<View,string>={leads:"Leads comerciales",customers:"Clientes",sales:"Ventas", "follow-ups":"Seguimientos",products:"Productos", "commercial-plans":"Planes comerciales"};

export function CrmWorkspace({ view, administrativeTenant }: { view: View; administrativeTenant?: string|null }) {
  const [items,setItems]=useState<RecordItem[]>([]); const [meta,setMeta]=useState<Meta>({stages:[],users:[],products:[],commercialPlans:[],leads:[],customers:[],role:"",activeFeatures:[]}); const [loading,setLoading]=useState(true); const [showCreate,setShowCreate]=useState(false); const [message,setMessage]=useState(""); const [selected,setSelected]=useState<RecordItem|null>(null);
  const load=useCallback(async()=>{setLoading(true);const [itemsResponse,metaResponse]=await Promise.all([fetch(`/api/crm/${view}`),fetch("/api/crm/meta")]);const itemResult=await itemsResponse.json();const metaResult=await metaResponse.json();if(itemsResponse.ok)setItems(itemResult.items);else setMessage(itemResult.message);if(metaResponse.ok)setMeta(metaResult);setLoading(false)},[view]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const canCatalog=meta.role==="COMPANY_ADMIN"; const users=meta.users.filter(user=>["AGENT","SUPERVISOR"].includes(user.role.code));
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch(`/api/crm/${view}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)return setMessage(result.message);setShowCreate(false);setMessage("");await load()}
  async function patch(id:string,data:Record<string,unknown>){const response=await fetch(`/api/crm/${view}/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)return setMessage(result.message);setMessage("");await load()}
  function edit(item:RecordItem){if(view==="sales"){const msisdn=window.prompt("MSISDN",item.msisdn??"");if(msisdn!==null){const sec=window.prompt("SEC",item.sec??"");const sot=window.prompt("SOT",item.sot??"");void patch(item.id,{msisdn,sec,sot})}return}if(view==="products"){const name=window.prompt("Nombre",item.name??"");if(name===null)return;const code=window.prompt("Código",item.code??"");if(code===null)return;const category=window.prompt("Categoría",item.category??"");if(category===null)return;void patch(item.id,{name,code,category});return}if(view==="commercial-plans"){const name=window.prompt("Nombre",item.name??"");if(name===null)return;const code=window.prompt("Código",item.code??"");if(code===null)return;const productId=window.prompt("ID del producto",item.productId??"");if(productId===null)return;const price=window.prompt("Precio",item.price??"");if(price===null)return;const fixedCharge=window.prompt("Cargo fijo",item.fixedCharge??"");if(fixedCharge===null)return;const validFrom=window.prompt("Vigente desde (AAAA-MM-DD)",item.validFrom?.slice(0,10)??"");if(validFrom===null)return;const validTo=window.prompt("Vigente hasta (AAAA-MM-DD)",item.validTo?.slice(0,10)??"");if(validTo===null)return;void patch(item.id,{name,code,productId,price,fixedCharge,validFrom,validTo});return}const name=window.prompt("Nombre",item.name)?.trim();if(name&&name!==item.name)void patch(item.id,{name})}
  const canCreate=!(["products","commercial-plans"].includes(view)&&!canCatalog);
  return <>{administrativeTenant&&<div className="admin-context"><span>◎</span><div><small>EMPRESA</small><strong>{administrativeTenant}</strong></div><div><small>MODO</small><strong>Administración</strong></div></div>}<section className="page-title crm-title"><div><span className="eyebrow">CRM · VENTAS TELECOM</span><h1>{titles[view]}</h1><p>Información comercial aislada para tu organización.</p></div>{canCreate&&<button className="primary" onClick={()=>setShowCreate(true)}>＋ Nuevo registro</button>}</section>
    <nav className="crm-tabs">{views.filter(item=>meta.activeFeatures.includes(item.id)).map(item=><Link className={item.id===view?"selected":""} key={item.id} href={`/crm/${item.id}`}>{item.label}</Link>)}{meta.activeFeatures.includes("commissions")&&<Link href="/crm/commissions">Comisiones</Link>}{meta.activeFeatures.includes("reconciliation")&&<Link href="/crm/reconciliation">Liquidaciones</Link>}{meta.activeFeatures.includes("finance")&&<Link href="/crm/finance">Finanzas</Link>}{meta.activeFeatures.includes("payroll")&&<Link href="/crm/payroll">Pago de Personal</Link>}{meta.activeFeatures.includes("commercial-management")&&<Link href="/crm/commercial-management">Gestión Comercial</Link>}{meta.activeFeatures.includes("promoter-space")&&<Link href="/crm/promoter-space">Espacio Promotor</Link>}</nav>
    {showCreate&&<section className="card crm-form"><div className="card-head"><div><h2>Crear {titles[view].toLowerCase()}</h2><p>Todos los datos se guardarán en el tenant de tu sesión.</p></div><button onClick={()=>setShowCreate(false)}>×</button></div><form onSubmit={create}><Fields view={view} meta={meta} users={users}/><button className="primary">Guardar</button></form></section>}
    {message&&<p className="form-error">{message}</p>}
    {selected&&view==="sales"&&<section className="card sale-detail"><div className="card-head"><div><h2>Detalle de venta</h2><p>{selected.id}</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="sale-detail-grid"><div><small>Cliente</small><strong>{selected.customerNameSnapshot}</strong><span>{selected.customerDocumentSnapshot??"Sin documento"}</span></div><div><small>Producto / plan</small><strong>{selected.productNameSnapshot}</strong><span>{selected.planNameSnapshot??"Sin plan"}</span></div><div><small>Promotor</small><strong>{selected.agent?.name}</strong><span>{selected.supervisor?.name??"Sin supervisor"}</span></div><div><small>Identificadores</small><strong>{selected.msisdn??"Sin MSISDN"}</strong><span>{selected.sec??"Sin SEC"} · {selected.sot??"Sin SOT"}</span></div></div><h3>Historial de estados</h3><div className="sale-history">{selected.statusHistory?.map(history=><div key={history.id}><span className="crm-state">{history.newStatus}</span><p><strong>{history.changedByUser.name}</strong><small>{new Date(history.changedAt).toLocaleString("es")}{history.reason?` · ${history.reason}`:""}</small></p></div>)}</div></section>}
    <section className="card crm-list">{loading?<div className="empty-core">Consultando CRM…</div>:items.length===0?<div className="empty-core">No hay registros todavía.</div>:items.map(item=><article key={item.id}><div className="crm-record-icon">{view==="leads"?"L":view==="customers"?"C":view==="sales"?"V":view==="follow-ups"?"S":view==="products"?"P":"PC"}</div><div className="crm-record-main"><strong>{view==="sales"?item.customerNameSnapshot:item.name??item.type??"Seguimiento"}</strong><small>{view==="leads"?`${item.phone} · ${item.origin}`:view==="customers"?`${item.phone}${item.email?` · ${item.email}`:""}`:view==="sales"?`${new Date(item.saleDate!).toLocaleDateString("es")} · ${item.productNameSnapshot} · ${item.msisdn??"Sin MSISDN"}`:view==="follow-ups"?`${item.lead?.name??item.customer?.name} · ${new Date(item.scheduledAt!).toLocaleString("es")}`:view==="products"?`${item.code} · ${item.category}`:`${item.code} · ${item.product?.name} · ${item.fixedCharge??item.price??"Sin cargo"}${item.validFrom?` · Desde ${new Date(item.validFrom).toLocaleDateString("es")}`:""}${item.validTo?` · Hasta ${new Date(item.validTo).toLocaleDateString("es")}`:""}`}</small></div>{view==="leads"&&<><select value={item.pipelineStageId} onChange={event=>void patch(item.id,{pipelineStageId:event.target.value})}>{meta.stages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><select value={item.assignedUserId??""} onChange={event=>void patch(item.id,{assignedUserId:event.target.value})}><option value="">Sin asignar</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></>}{view==="customers"&&<span className="crm-owner">{item.ownerUser?.name??"Sin responsable"}</span>}{view==="sales"&&<><span className="crm-owner">{item.agent?.name}</span><select value={item.status} onChange={event=>void patch(item.id,{status:event.target.value})}>{["REGISTRADA","EN_VALIDACION","APROBADA","ACTIVADA","RECHAZADA","CANCELADA"].map(status=><option key={status}>{status}</option>)}</select><button className="secondary" onClick={()=>setSelected(item)}>Detalle</button></>}{view==="follow-ups"&&<><span className={`crm-state ${item.status?.toLowerCase()}`}>{item.status}</span><button className="secondary" onClick={()=>void patch(item.id,{status:item.status==="COMPLETED"?"PENDING":"COMPLETED"})}>{item.status==="COMPLETED"?"Reabrir":"Completar"}</button></>}{["products","commercial-plans"].includes(view)&&<><span className={`crm-state ${item.status?.toLowerCase()}`}>{item.status}</span>{canCatalog&&<button className="secondary" onClick={()=>void patch(item.id,{status:item.status==="ACTIVE"?"INACTIVE":"ACTIVE"})}>{item.status==="ACTIVE"?"Desactivar":"Activar"}</button>}</>} {view!=="follow-ups"&&<button className="crm-edit" onClick={()=>edit(item)}>Editar</button>}</article>)}</section></>;
}

function Fields({view,meta,users}:{view:View;meta:Meta;users:Meta["users"]}){
  if(view==="leads")return <><label>Nombre<input name="name" required/></label><label>Teléfono<input name="phone" required/></label><label>Email<input name="email" type="email"/></label><label>Origen<input name="origin" required/></label><label>Estado<select name="pipelineStageId" required>{meta.stages.map(stage=><option value={stage.id} key={stage.id}>{stage.name}</option>)}</select></label><label>Agente<select name="assignedUserId"><option value="">Sin asignar</option>{users.map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label><label className="wide">Notas<textarea name="notes"/></label></>;
  if(view==="customers")return <><label>Nombre<input name="name" required/></label><label>Documento<input name="document"/></label><label>Teléfono<input name="phone" required/></label><label>Email<input name="email" type="email"/></label><label>Ciudad<input name="city"/></label><label>Dirección<input name="address"/></label><label>Responsable<select name="ownerUserId"><option value="">Sin asignar</option>{users.map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label></>;
  if(view==="sales")return <><label>Lead opcional<select name="leadId"><option value="">Sin lead</option>{meta.leads.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Cliente<select name="customerId" required>{meta.customers.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Producto<select name="productId" required>{meta.products.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Plan comercial<select name="commercialPlanId"><option value="">Sin plan</option>{meta.commercialPlans.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Tipo de operación<select name="transactionType" required>{["PORTABILIDAD_POSTPAGO","ALTA_NUEVA_POSTPAGO","MIGRACION","PREPAGO","RENOVACION","LINEA_FIJA","INTERNET_FIJO","OTRO"].map(type=><option key={type}>{type}</option>)}</select></label><label>Promotor<select name="agentId" required>{users.filter(user=>user.role.code==="AGENT").map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label><label>Fecha<input name="saleDate" type="date" required/></label><label>SEC<input name="sec"/></label><label>SOT<input name="sot"/></label><label>MSISDN<input name="msisdn"/></label><label>Canal<input name="salesChannel"/></label><label>Punto de venta<input name="pointOfSale"/></label><label className="wide">Observaciones<textarea name="notes"/></label></>;
  if(view==="follow-ups")return <><label>Relacionar con<select name="leadId"><option value="">Seleccionar lead</option>{meta.leads.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>O cliente<select name="customerId"><option value="">Seleccionar cliente</option>{meta.customers.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Asignar a<select name="assignedUserId" required>{users.map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label><label>Fecha y hora<input name="scheduledAt" type="datetime-local" required/></label><label>Tipo<input name="type" required placeholder="Llamada, visita…"/></label><label className="wide">Notas<textarea name="notes"/></label></>;
  if(view==="products")return <><label>Nombre<input name="name" required/></label><label>Código<input name="code" required/></label><label>Categoría<input name="category" required/></label></>;
  return <><label>Nombre<input name="name" required/></label><label>Código<input name="code" required/></label><label>Producto<select name="productId" required>{meta.products.map(product=><option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Precio<input name="price" type="number" step="0.01"/></label><label>Cargo fijo<input name="fixedCharge" type="number" step="0.01"/></label><label>Vigente desde<input name="validFrom" type="date"/></label><label>Vigente hasta<input name="validTo" type="date"/></label></>;
}
