"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Option={id:string;name:string;productId?:string};
type Meta={products:Option[];commercialPlans:Option[];role:string;activeFeatures:string[]};
type Rule={id:string;name:string;code:string;productId:string|null;commercialPlanId:string|null;transactionType:string|null;effectiveFrom:string;effectiveTo:string|null;active:boolean;expectedCompanyIncomeType:string|null;expectedCompanyIncomeValue:string|null;promoterCommissionType:string|null;promoterCommissionValue:string|null;supervisorCommissionType:string|null;supervisorCommissionValue:string|null;product:Option|null;commercialPlan:Option|null;_count:{calculations:number}};
type Draft={name:string;code:string;productId:string;commercialPlanId:string;transactionType:string;effectiveFrom:string;effectiveTo:string;expectedCompanyIncomeType:string;expectedCompanyIncomeValue:string;promoterCommissionType:string;promoterCommissionValue:string;supervisorCommissionType:string;supervisorCommissionValue:string;active:boolean};
const empty:Draft={name:"",code:"",productId:"",commercialPlanId:"",transactionType:"",effectiveFrom:"",effectiveTo:"",expectedCompanyIncomeType:"",expectedCompanyIncomeValue:"",promoterCommissionType:"",promoterCommissionValue:"",supervisorCommissionType:"",supervisorCommissionValue:"",active:true};
const operations=["PORTABILIDAD","ALTA_NUEVA","PORTABILIDAD_POSTPAGO","ALTA_NUEVA_POSTPAGO","MIGRACION","PREPAGO","RENOVACION","LINEA_FIJA","INTERNET_FIJO","OTRO"];
const navigation=[{id:"leads",label:"Leads"},{id:"customers",label:"Clientes"},{id:"sales",label:"Ventas"},{id:"follow-ups",label:"Seguimientos"},{id:"products",label:"Productos"},{id:"commercial-plans",label:"Planes comerciales"},{id:"commissions",label:"Comisiones"},{id:"reconciliation",label:"Liquidaciones"},{id:"finance",label:"Finanzas"},{id:"payroll",label:"Pago de Personal"},{id:"commercial-management",label:"Gestión Comercial"},{id:"promoter-space",label:"Espacio Promotor"}];

export function EconomicRulesWorkspace({administrativeTenant}:{administrativeTenant?:string|null}){
  const[meta,setMeta]=useState<Meta>({products:[],commercialPlans:[],role:"",activeFeatures:[]});
  const[rules,setRules]=useState<Rule[]>([]),[draft,setDraft]=useState<Draft>(empty),[editing,setEditing]=useState<string|null>(null);
  const[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[impact,setImpact]=useState<{count:number;periodFrom:string|null;periodTo:string|null}|null>(null);
  const[filters,setFilters]=useState({productId:"",commercialPlanId:"",transactionType:""});
  const canWrite=["SUPER_ADMIN","COMPANY_ADMIN"].includes(meta.role);
  const load=useCallback(async()=>{setLoading(true);const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const[metaResponse,rulesResponse]=await Promise.all([fetch("/api/crm/meta"),fetch(`/api/crm/economic-rules?${query}`)]);const metaResult=await metaResponse.json(),rulesResult=await rulesResponse.json();if(metaResponse.ok)setMeta(metaResult);if(rulesResponse.ok){setRules(rulesResult.items);setMessage("")}else setMessage(rulesResult.message);setLoading(false)},[filters]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const plans=useMemo(()=>meta.commercialPlans.filter(plan=>!draft.productId||plan.productId===draft.productId),[meta.commercialPlans,draft.productId]);
  const selectedProduct=meta.products.find(item=>item.id===draft.productId)?.name??"Todos los productos";
  const selectedPlan=meta.commercialPlans.find(item=>item.id===draft.commercialPlanId)?.name??"Cualquier plan";
  function update<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(current=>({...current,[key]:value,...(key==="productId"&&!meta.commercialPlans.some(plan=>plan.id===current.commercialPlanId&&plan.productId===value)?{commercialPlanId:""}:{})}));setImpact(null)}
  function begin(rule?:Rule){setEditing(rule?.id??null);setDraft(rule?{name:rule.name,code:rule.code,productId:rule.productId??"",commercialPlanId:rule.commercialPlanId??"",transactionType:rule.transactionType??"",effectiveFrom:rule.effectiveFrom.slice(0,10),effectiveTo:rule.effectiveTo?.slice(0,10)??"",expectedCompanyIncomeType:rule.expectedCompanyIncomeType??"",expectedCompanyIncomeValue:rule.expectedCompanyIncomeValue??"",promoterCommissionType:rule.promoterCommissionType??"",promoterCommissionValue:rule.promoterCommissionValue??"",supervisorCommissionType:rule.supervisorCommissionType??"",supervisorCommissionValue:rule.supervisorCommissionValue??"",active:rule.active}:empty);setImpact(null);setMessage("");setOpen(true)}
  async function save(event:React.FormEvent){event.preventDefault();const response=await fetch(editing?`/api/crm/economic-rules/${editing}`:"/api/crm/economic-rules",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok)return setMessage(result.message);setOpen(false);setMessage("Regla guardada. Los cálculos históricos no fueron sobrescritos.");await load()}
  async function simulate(){const response=await fetch("/api/crm/economic-rules/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}),result=await response.json();if(!response.ok)return setMessage(result.message);setImpact(result);setMessage("")}
  async function toggle(rule:Rule){const response=await fetch(`/api/crm/economic-rules/${rule.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!rule.active})}),result=await response.json();if(!response.ok)return setMessage(result.message);await load()}
  return <>{administrativeTenant&&<div className="admin-context"><span>◎</span><div><small>EMPRESA</small><strong>{administrativeTenant}</strong></div><div><small>MODO</small><strong>Administración</strong></div></div>}
    <section className="page-title crm-title"><div><span className="eyebrow">CRM · MOTOR ECONÓMICO</span><h1>Comisiones y reglas económicas</h1><p>Define cómo genera valor cada venta sin mezclar pagos ni liquidaciones.</p></div>{canWrite&&<button className="primary" onClick={()=>begin()}>＋ Nueva regla</button>}</section>
    <nav className="crm-tabs">{navigation.filter(item=>meta.activeFeatures.includes(item.id)).map(item=><Link className={item.id==="commissions"?"selected":""} key={item.id} href={`/crm/${item.id}`}>{item.label}</Link>)}</nav>
    <section className="economic-summary"><article><small>REGLAS VISIBLES</small><strong>{rules.length}</strong><span>Aisladas para esta empresa</span></article><article><small>PRIORIDAD</small><strong>Más específica</strong><span>Producto + plan + operación</span></article><article><small>BASE PORCENTUAL</small><strong>Monto de venta</strong><span>Snapshot saleAmount</span></article><article><small>MARGEN</small><strong>Preliminar</strong><span>No es utilidad neta</span></article></section>
    <section className="card economic-filters"><label>Producto<select value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value,commercialPlanId:""})}><option value="">Todos</option>{meta.products.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Plan<select value={filters.commercialPlanId} onChange={e=>setFilters({...filters,commercialPlanId:e.target.value})}><option value="">Todos</option>{meta.commercialPlans.filter(plan=>!filters.productId||plan.productId===filters.productId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Operación<select value={filters.transactionType} onChange={e=>setFilters({...filters,transactionType:e.target.value})}><option value="">Todas</option>{operations.map(item=><option key={item}>{item}</option>)}</select></label></section>
    {open&&<section className="card economic-editor"><div className="card-head"><div><h2>{editing?"Editar regla":"Nueva regla económica"}</h2><p>Los campos económicos vacíos permanecen sin configurar; no se convierten en cero.</p></div><button onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></div><form onSubmit={save}>
      <div className="economic-fields"><label>Nombre de regla<input required value={draft.name} onChange={e=>update("name",e.target.value)}/></label><label>Código<input required value={draft.code} onChange={e=>update("code",e.target.value.toUpperCase())}/></label><label>Producto<select value={draft.productId} onChange={e=>update("productId",e.target.value)}><option value="">Cualquier producto</option>{meta.products.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Plan opcional<select value={draft.commercialPlanId} onChange={e=>update("commercialPlanId",e.target.value)}><option value="">Cualquier plan</option>{plans.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Operación opcional<select value={draft.transactionType} onChange={e=>update("transactionType",e.target.value)}><option value="">Cualquier operación</option>{operations.map(item=><option key={item}>{item}</option>)}</select></label><label>Vigencia desde<input required type="date" value={draft.effectiveFrom} onChange={e=>update("effectiveFrom",e.target.value)}/></label><label>Vigencia hasta<input type="date" value={draft.effectiveTo} onChange={e=>update("effectiveTo",e.target.value)}/></label><EconomicComponent label="Ingreso esperado empresa" type={draft.expectedCompanyIncomeType} value={draft.expectedCompanyIncomeValue} onType={v=>update("expectedCompanyIncomeType",v)} onValue={v=>update("expectedCompanyIncomeValue",v)}/><EconomicComponent label="Comisión promotor" type={draft.promoterCommissionType} value={draft.promoterCommissionValue} onType={v=>update("promoterCommissionType",v)} onValue={v=>update("promoterCommissionValue",v)}/><EconomicComponent label="Comisión supervisor" type={draft.supervisorCommissionType} value={draft.supervisorCommissionValue} onType={v=>update("supervisorCommissionType",v)} onValue={v=>update("supervisorCommissionValue",v)}/><label className="economic-active"><input type="checkbox" checked={draft.active} onChange={e=>update("active",e.target.checked)}/> Regla activa</label></div>
      <aside className="economic-preview"><span>PREVISUALIZACIÓN</span><h3>Esta regla aplicará a ventas que cumplan:</h3><dl><div><dt>Producto</dt><dd>{selectedProduct}</dd></div><div><dt>Plan</dt><dd>{selectedPlan}</dd></div><div><dt>Operación</dt><dd>{draft.transactionType||"Cualquier operación"}</dd></div><div><dt>Vigencia</dt><dd>{draft.effectiveFrom||"Sin definir"} → {draft.effectiveTo||"Sin fecha final"}</dd></div></dl>{impact&&<div className="impact-result"><strong>{impact.count} ventas históricas</strong><span>{impact.periodFrom?`${new Date(impact.periodFrom).toLocaleDateString("es-PE")} → ${new Date(impact.periodTo!).toLocaleDateString("es-PE")}`:"Sin coincidencias"}</span><small>Lectura solamente · no se modificó ninguna venta</small></div>}<button type="button" className="secondary" onClick={()=>void simulate()}>Ver ventas afectadas</button><button className="primary">Guardar regla</button></aside>
    </form></section>}
    {message&&<p className="form-error">{message}</p>}
    <section className="card economic-list">{loading?<div className="empty-core">Consultando reglas…</div>:rules.length===0?<div className="economic-empty"><span>◇</span><h2>No hay reglas económicas configuradas</h2><p>Las ventas permanecen SIN REGLA y sus montos económicos siguen vacíos.</p></div>:rules.map(rule=><article key={rule.id}><div className="rule-head"><span className={`crm-state ${rule.active?"":"inactive"}`}>{rule.active?"ACTIVA":"INACTIVA"}</span><div><strong>{rule.name}</strong><small>{rule.code}</small></div><div className="rule-actions">{canWrite&&<><button className="secondary" onClick={()=>begin(rule)}>Editar</button><button className="secondary" onClick={()=>void toggle(rule)}>{rule.active?"Desactivar":"Activar"}</button></>}</div></div><div className="rule-scope"><span><small>PRODUCTO</small>{rule.product?.name??"Cualquiera"}</span><span><small>PLAN</small>{rule.commercialPlan?.name??"Cualquiera"}</span><span><small>OPERACIÓN</small>{rule.transactionType??"Cualquiera"}</span><span><small>VIGENCIA</small>{new Date(rule.effectiveFrom).toLocaleDateString("es-PE")} → {rule.effectiveTo?new Date(rule.effectiveTo).toLocaleDateString("es-PE"):"Sin fin"}</span><span><small>SNAPSHOTS</small>{rule._count.calculations}</span></div><div className="rule-values"><Value label="Ingreso empresa" type={rule.expectedCompanyIncomeType} value={rule.expectedCompanyIncomeValue}/><Value label="Promotor" type={rule.promoterCommissionType} value={rule.promoterCommissionValue}/><Value label="Supervisor" type={rule.supervisorCommissionType} value={rule.supervisorCommissionValue}/></div></article>)}</section>
  </>;
}

function EconomicComponent({label,type,value,onType,onValue}:{label:string;type:string;value:string;onType:(v:string)=>void;onValue:(v:string)=>void}){return <div className="economic-component"><label>{label}<input type="number" min="0" step="0.0001" placeholder="Sin configurar" value={value} onChange={e=>onValue(e.target.value)}/></label><label>Tipo de cálculo<select value={type} onChange={e=>onType(e.target.value)}><option value="">Sin configurar</option><option value="FIXED">Monto fijo</option><option value="PERCENTAGE">Porcentaje del monto de venta</option></select></label></div>}
function Value({label,type,value}:{label:string;type:string|null;value:string|null}){return <span><small>{label}</small><strong>{value===null?"Sin configurar":type==="PERCENTAGE"?`${Number(value)}%`:`S/ ${Number(value).toFixed(2)}`}</strong></span>}
