"use client";
import { useState } from "react";
import { roleLandingPath } from "@/lib/role-routes";

type TenantLoginBranding = { displayName: string; initials: string; logoUrl: string | null; primaryColor: string | null; secondaryColor: string | null; loginTitle: string | null; loginSubtitle: string | null; loginBackgroundUrl: string | null };
export function LoginForm({ branding, tenantSlug, initialEmail }: { branding?: TenantLoginBranding; tenantSlug?: string; initialEmail?: string }) {
  const [loading,setLoading]=useState(false),[error,setError]=useState("");
  async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password"),tenantSlug})});const result=await response.json();setLoading(false);if(!response.ok)return setError(result.message??"No fue posible iniciar sesión.");window.location.href=roleLandingPath(result.session.user.role)}
  const name=branding?.displayName??"MentoriFY",initials=branding?.initials??"M";
  const style={"--tenant-primary":branding?.primaryColor??"#6957d5","--tenant-secondary":branding?.secondaryColor??"#242044"} as React.CSSProperties;
  return <main className={`login-page ${branding?"tenant-login":""}`} style={style}><section className="login-panel"><div className="brand login-brand"><span className="brand-mark" style={branding?.logoUrl?{backgroundImage:`url(${branding.logoUrl})`}:undefined}>{branding?.logoUrl?"":initials}</span><div><strong>{name}</strong><small>{branding?"Portal empresarial":"Enterprise Platform"}</small></div></div><div className="login-copy"><span className="eyebrow">ACCESO SEGURO</span><h1>{branding?.loginTitle??"Bienvenido de nuevo"}</h1><p>{branding?.loginSubtitle??"Ingresa a tu espacio de trabajo con tus credenciales."}</p></div><form onSubmit={login}><label>Correo electrónico<input name="email" type="email" autoComplete="username" required placeholder="tu@empresa.com" defaultValue={initialEmail} /></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required /></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading?"Verificando…":"Iniciar sesión"}</button></form><small className="login-security">Sesión protegida · Acceso limitado a tu organización</small></section><aside style={branding?.loginBackgroundUrl?{backgroundImage:`linear-gradient(#171b32cc,#242044cc),url(${branding.loginBackgroundUrl})`}:undefined}><span>{branding?name.toUpperCase():"MENTORIFY CORE SAAS"}</span><h2>{branding?"Tu espacio de trabajo.":<>Una plataforma.<br/>Cada empresa, aislada.</>}</h2><p>Acceso protegido y datos aislados para tu organización.</p><div><i>✓</i> Sesiones seguras</div><div><i>✓</i> Información de tu empresa</div><div><i>✓</i> Contraseñas cifradas</div></aside></main>;
}
