/* eslint-disable @next/next/no-html-link-for-pages -- authenticated XLSX downloads require normal anchors */
"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
type Provider={id:string;name:string;legalName:string|null;code:string;active:boolean};
type Import={id:string;period:string;settlementDate:string;originalFileName:string;status:string;rowCount:number;matchedCount:number;differenceCount:number;pendingCount:number;externalOnlyCount:number;uploadedAt:string;provider:Provider;uploadedBy:{name:string;email:string};metrics:{recognized:number;conforme:number;difference:number;notFound:number;notSettled:number;recognizedAmount:string;differenceAmount:string}};
type Result={id:string;expectedAmount:string|null;recognizedAmount:string|null;differenceAmount:string|null;status:string;matchStatus:string;matchedBy:string|null;reconciliation:{provider:Provider;period:string};sale:{id:string;saleDate:string;customerNameSnapshot:string;customerDocumentSnapshot:string|null;productNameSnapshot:string;planNameSnapshot:string|null;transactionType:string;sec:string|null;sot:string|null;msisdn:string|null;historicalAdvisorName:string|null;customer:{phone:string}}|null};
type Data={imports:Import[];results:Result[];summary:{sales:number;counts:Record<string,number>;expected:string|null;recognized:string|null;difference:string|null}};
type Meta={products:Array<{id:string;name:string}>;commercialPlans:Array<{id:string;name:string;productId:string}>;activeFeatures:string[]};
const nav=[['leads','Leads'],['customers','Clientes'],['sales','Ventas'],['follow-ups','Seguimientos'],['products','Productos'],['commercial-plans','Planes comerciales'],['commissions','Comisiones'],['reconciliation','Liquidaciones'],['finance','Finanzas'],['payroll','Pago de Personal'],['commercial-management','Gestión Comercial'],['promoter-space','Espacio Promotor']];
const statuses=["CONFORME","DIFERENCIA","NO_LIQUIDADO","PENDIENTE","NO_ENCONTRADO","REQUIERE_REVISION"];
const emptyFilters={period:"",providerId:"",status:"",search:"",productId:"",commercialPlanId:"",transactionType:"",advisor:""};
export function ReconciliationWorkspace({administrativeTenant}:{administrativeTenant?:string|null}){
  const[providers,setProviders]=useState<Provider[]>([]),[meta,setMeta]=useState<Meta>({products:[],commercialPlans:[],activeFeatures:[]}),[data,setData]=useState<Data>({imports:[],results:[],summary:{sales:0,counts:{},expected:null,recognized:null,difference:null}}),[filters,setFilters]=useState(emptyFilters),[open,setOpen]=useState(false),[providerOpen,setProviderOpen]=useState(false),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value));const[a,b,m]=await Promise.all([fetch(`/api/crm/reconciliation?${query}`),fetch('/api/crm/reconciliation/providers'),fetch('/api/crm/operational-meta')]),[ar,br,mr]=await Promise.all([a.json(),b.json(),m.json()]);if(a.ok){setData(ar);setMessage("")}else setMessage(ar.message);if(b.ok)setProviders(br.items);if(m.ok)setMeta(mr);setLoading(false)},[filters]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function createProvider(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,response=await fetch('/api/crm/reconciliation/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))}),result=await response.json();if(!response.ok)return setMessage(result.message);form.reset();setMessage('Empresa proveedora registrada para este tenant.');await load()}
  async function toggleProvider(item:Provider){const response=await fetch(`/api/crm/reconciliation/providers/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!item.active})}),result=await response.json();if(!response.ok)return setMessage(result.message);await load()}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const response=await fetch('/api/crm/reconciliation',{method:'POST',body:new FormData(event.currentTarget)}),result=await response.json();if(!response.ok)return setMessage(result.message);setOpen(false);setMessage('Liquidación procesada. Las ventas CRM no fueron modificadas.');await load()}
  const c=data.summary.counts;return <>{administrativeTenant&&<div className="admin-context"><span>◎</span><div><small>EMPRESA</small><strong>{administrativeTenant}</strong></div></div>}
  <section className="page-title crm-title"><div><span className="eyebrow">CRM · LIQUIDACIONES COMERCIALES</span><h1>Liquidaciones</h1><p>Compara ventas CRM con archivos de empresas proveedoras sin alterar la operación comercial.</p></div><div className="reconciliation-actions"><button className="secondary" onClick={()=>setProviderOpen(true)}>Empresas proveedoras</button><a className="secondary template-link" href="/api/crm/reconciliation/template">Descargar plantilla</a><button className="primary" onClick={()=>setOpen(true)}>＋ Nueva liquidación</button></div></section>
  <nav className="crm-tabs">{nav.filter(([id])=>meta.activeFeatures.includes(id)).map(([id,text])=><Link className={id==='reconciliation'?'selected':''} key={id} href={`/crm/${id}`}>{text}</Link>)}</nav>
  <section className="reconciliation-kpis"><Kpi label="Ventas CRM" value={data.summary.sales}/><Kpi label="Reconocidas" value={(c.CONFORME??0)+(c.DIFERENCIA??0)+(c.PENDIENTE??0)}/><Kpi label="Conformes" value={c.CONFORME??0}/><Kpi label="Con diferencias" value={c.DIFERENCIA??0}/><Kpi label="No liquidadas" value={c.NO_LIQUIDADO??0}/><Kpi label="Pendientes" value={(c.PENDIENTE??0)+(c.REQUIERE_REVISION??0)}/><Kpi label="Monto esperado" value={money(data.summary.expected)}/><Kpi label="Monto reconocido" value={money(data.summary.recognized)}/><Kpi label="Diferencia total" value={money(data.summary.difference)}/></section>
  <section className="reconciliation-shortcuts">{[['CONFORME','Ver conformes'],['DIFERENCIA','Ver diferencias'],['NO_LIQUIDADO','Ver no liquidadas'],['PENDIENTE','Ver pendientes'],['NO_ENCONTRADO','Ver no encontradas'],['REQUIERE_REVISION','Externos / revisión']].map(([status,text])=><button key={status} className={filters.status===status?'active':''} onClick={()=>setFilters({...filters,status})}>{text}</button>)}</section>
  <section className="card reconciliation-filters"><label>Buscar<input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="DNI, cliente, teléfono, SEC o SOT"/></label><label>Periodo<input type="month" value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}/></label><label>Empresa proveedora<select value={filters.providerId} onChange={e=>setFilters({...filters,providerId:e.target.value})}><option value="">Todas</option>{providers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Estado<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option>{statuses.map(item=><option key={item}>{label(item)}</option>)}</select></label><label>Producto<select value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value,commercialPlanId:""})}><option value="">Todos</option>{meta.products.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Plan<select value={filters.commercialPlanId} onChange={e=>setFilters({...filters,commercialPlanId:e.target.value})}><option value="">Todos</option>{meta.commercialPlans.filter(item=>!filters.productId||item.productId===filters.productId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Operación<input value={filters.transactionType} onChange={e=>setFilters({...filters,transactionType:e.target.value.toUpperCase()})}/></label><label>Asesor<input value={filters.advisor} onChange={e=>setFilters({...filters,advisor:e.target.value})}/></label><button className="secondary" onClick={()=>setFilters(emptyFilters)}>Limpiar</button><a className="secondary export-link" href={`/api/crm/reconciliation/export?status=${filters.status||'DIFERENCIA'}`}>Exportar diferencias</a></section>{message&&<p className="form-error">{message}</p>}
  <section className="card reconciliation-table"><div className="table-scroll"><table className="operational-table"><thead><tr><th>DNI</th><th>Cliente</th><th>Teléfono</th><th>SEC / SOT</th><th>Fecha</th><th>Producto / plan</th><th>Empresa proveedora</th><th>Esperado</th><th>Reconocido</th><th>Diferencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{data.results.map(item=><tr key={item.id}><td>{item.sale?.customerDocumentSnapshot||'—'}</td><td><strong>{item.sale?.customerNameSnapshot||'Registro externo'}</strong></td><td>{item.sale?.msisdn||item.sale?.customer.phone||'—'}</td><td><strong>{item.sale?.sec?`SEC: ${item.sale.sec}`:'—'}</strong>{item.sale?.sot&&<small>SOT: {item.sale.sot}</small>}</td><td>{item.sale?new Date(item.sale.saleDate).toLocaleDateString('es-PE'):'—'}</td><td><strong>{item.sale?.productNameSnapshot||'—'}</strong>{item.sale?.planNameSnapshot&&<small>{item.sale.planNameSnapshot}</small>}</td><td>{item.reconciliation.provider.name}</td><td>{money(item.expectedAmount)}</td><td>{money(item.recognizedAmount)}</td><td>{money(item.differenceAmount)}</td><td><span className={`operational-status ${item.status.toLowerCase()}`}>{label(item.status)}</span></td><td><button className="secondary" title={item.matchedBy||item.matchStatus}>Revisar</button></td></tr>)}</tbody></table></div>{!loading&&!data.results.length&&<div className="operational-empty"><strong>Sin liquidaciones procesadas</strong><span>Carga un archivo real cuando la empresa proveedora entregue su liquidación.</span></div>}</section>
  <section className="settlement-history"><div className="section-heading"><div><span className="eyebrow">TRAZABILIDAD</span><h2>Historial de liquidaciones</h2></div><span>{data.imports.length} procesos</span></div>{data.imports.length?<div className="table-scroll card"><table className="operational-table"><thead><tr><th>Empresa</th><th>Periodo / fecha</th><th>Procesado por</th><th>Recibidos</th><th>Reconocidos</th><th>Conformes</th><th>Diferencias</th><th>No encontrados</th><th>Monto reconocido</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>{data.imports.map(item=><tr key={item.id}><td><strong>{item.provider.name}</strong>{item.provider.legalName&&<small>{item.provider.legalName}</small>}</td><td><strong>{item.period}</strong><small>{new Date(item.settlementDate).toLocaleDateString('es-PE')}</small></td><td><strong>{item.uploadedBy.name}</strong><small>{item.uploadedBy.email}</small></td><td>{item.rowCount}</td><td>{item.metrics.recognized}</td><td>{item.metrics.conforme}</td><td>{item.metrics.difference}</td><td>{item.metrics.notFound}</td><td>{money(item.metrics.recognizedAmount)}</td><td>{money(item.metrics.differenceAmount)}</td><td><span className={`operational-status ${item.status.toLowerCase()}`}>{label(item.status)}</span></td></tr>)}</tbody></table></div>:<div className="card operational-empty"><strong>Sin historial todavía</strong><span>Los procesos reales aparecerán aquí con su trazabilidad.</span></div>}</section>
  {open&&<Modal title="Nueva liquidación" close={()=>setOpen(false)}><form className="reconciliation-form" onSubmit={upload}><div className="template-help wide"><span>¿Aún no tienes el archivo estándar?</span><a href="/api/crm/reconciliation/template">Descargar plantilla</a></div><label>Empresa proveedora / Entidad pagadora<select name="providerId" required><option value="">Seleccionar</option>{providers.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Periodo<input name="period" type="month" required/></label><label>Fecha de liquidación<input name="settlementDate" type="date" required/></label><label>Archivo Excel<input name="file" type="file" accept=".xlsx,.xls" required/></label><label className="wide">Observaciones<textarea name="notes"/></label><button className="primary wide">Procesar liquidación</button></form></Modal>}
  {providerOpen&&<Modal title="Empresas proveedoras / Entidades pagadoras" close={()=>setProviderOpen(false)}><form className="reconciliation-form" onSubmit={createProvider}><label>Nombre comercial<input name="name" required/></label><label>Razón social opcional<input name="legalName"/></label><label>Código interno opcional<input name="code"/></label><label className="provider-active"><input name="active" type="checkbox" defaultChecked value="true"/> Activa al crear</label><button className="primary wide">Guardar empresa proveedora</button></form><section className="provider-list">{providers.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.legalName||'Sin razón social'} · {item.code}</small></div><button className="secondary" onClick={()=>void toggleProvider(item)}>{item.active?'Desactivar':'Activar'}</button></article>)}</section></Modal>}</>;
}
function Kpi({label,value}:{label:string;value:string|number}){return <article><small>{label}</small><strong>{value}</strong></article>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="detail-backdrop"><aside className="detail-panel reconciliation-modal"><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</aside></div>}
function money(value:string|null){return value===null?'—':`S/ ${Number(value).toFixed(2)}`}
function label(value:string){return value.replaceAll('_',' ')}
