import { assignedScope, crmError, requireCrmContext, validateAssignableUser } from "@/lib/crm-access";
import { getPrisma } from "@/lib/prisma";
import { requireCrmFeature } from "@/lib/vertical-template";

export async function PATCH(request: Request, { params }: { params: Promise<{ resource: string; id: string }> }) {
  try {
    const context = await requireCrmContext(); const { resource, id } = await params; await requireCrmFeature(context.tenantId,resource); const body = await request.json(); const prisma = getPrisma();
    if (resource === "leads") {
      const current = await prisma.lead.findFirst({ where: { id, tenantId: context.tenantId, ...assignedScope(context, "assignedUserId") } }); if (!current) throw new Response("Lead fuera de alcance", { status: 403 });
      let assignedUserId = body.assignedUserId as string | undefined; let supervisorId: string | null | undefined;
      if (context.role === "AGENT") assignedUserId = context.userId;
      if (assignedUserId) { const user = await validateAssignableUser(context, assignedUserId); supervisorId = user.supervisorId ?? (user.role.code === "SUPERVISOR" ? user.id : null); }
      if (body.pipelineStageId && !await prisma.pipelineStage.findFirst({ where: { id: body.pipelineStageId, tenantId: context.tenantId } })) throw new Response("Estado comercial de otro tenant", { status: 403 });
      const stageChanged = body.pipelineStageId && body.pipelineStageId !== current.pipelineStageId;
      const item = await prisma.$transaction(async (tx) => { const updated = await tx.lead.update({ where: { id }, data: { name: body.name, document: body.document, phone: body.phone, email: body.email, origin: body.origin, notes: body.notes, assignedUserId, supervisorId, pipelineStageId: body.pipelineStageId } }); if (stageChanged) await tx.leadStageHistory.create({ data: { tenantId: context.tenantId, leadId: id, pipelineStageId: body.pipelineStageId, changedByUserId: context.userId } }); return updated; }); return Response.json({ item });
    }
    if (resource === "customers") { const current = await prisma.customer.findFirst({ where: { id, tenantId: context.tenantId, ...assignedScope(context, "ownerUserId") } }); if (!current) throw new Response("Cliente fuera de alcance", { status: 403 }); let ownerUserId = body.ownerUserId; if (context.role === "AGENT") ownerUserId = context.userId; if (ownerUserId) await validateAssignableUser(context, ownerUserId); const item = await prisma.customer.update({ where: { id }, data: { name: body.name, document: body.document, phone: body.phone, email: body.email, city: body.city, address: body.address, status: body.status, ownerUserId } }); return Response.json({ item }); }
    if (resource === "follow-ups") { const current = await prisma.followUp.findFirst({ where: { id, tenantId: context.tenantId, ...assignedScope(context, "assignedUserId") } }); if (!current) throw new Response("Seguimiento fuera de alcance", { status: 403 }); const status = body.status; const item = await prisma.followUp.update({ where: { id }, data: { scheduledAt: body.scheduledAt ? new Date(body.scheduledAt) : undefined, type: body.type, notes: body.notes, status, completedAt: status === "COMPLETED" ? new Date() : status === "PENDING" ? null : undefined } }); return Response.json({ item }); }
    if (!["COMPANY_ADMIN","SUPER_ADMIN"].includes(context.role)) throw new Response("Solo administración gestiona catálogo", { status: 403 });
    if (resource === "products") { if (!await prisma.product.findFirst({ where: { id, tenantId: context.tenantId } })) throw new Response("Producto de otro tenant", { status: 403 }); const item = await prisma.product.update({ where: { id }, data: { name: body.name?.trim(), code: body.code?.trim().toUpperCase(), category: body.category?.trim().toUpperCase(), status: body.status } }); return Response.json({ item }); }
    if (resource === "commercial-plans") { if (!await prisma.commercialPlan.findFirst({ where: { id, tenantId: context.tenantId } })) throw new Response("Plan comercial de otro tenant", { status: 403 }); if (body.productId && !await prisma.product.findFirst({ where: { id: body.productId, tenantId: context.tenantId } })) throw new Response("Producto de otro tenant", { status: 403 }); const item = await prisma.commercialPlan.update({ where: { id }, data: { productId: body.productId, name: body.name?.trim(), code: body.code?.trim().toUpperCase(), price: body.price === "" ? null : body.price === undefined ? undefined : Number(body.price), fixedCharge: body.fixedCharge === "" ? null : body.fixedCharge === undefined ? undefined : Number(body.fixedCharge), validFrom: body.validFrom === "" ? null : body.validFrom ? new Date(body.validFrom) : undefined, validTo: body.validTo === "" ? null : body.validTo ? new Date(body.validTo) : undefined, status: body.status } }); return Response.json({ item }); }
    return Response.json({ message: "Recurso no encontrado" }, { status: 404 });
  } catch (error) { return crmError(error); }
}
