import { NextResponse } from "next/server";
import { hash } from "bcryptjs";
import { getPrisma, isDatabaseConfigured } from "@/lib/prisma";
import { serializeTenant, slugify, tenantInclude } from "@/lib/core-data";
import { isSuperAdmin, requireSession } from "@/lib/auth";

function unavailable(){return NextResponse.json({error:"DATABASE_NOT_CONFIGURED",message:"Configura DATABASE_URL para usar la persistencia PostgreSQL."},{status:503})}
function optional(value:unknown){const text=typeof value==="string"?value.trim():"";return text||null}
export async function GET(){if(!isDatabaseConfigured())return unavailable();try{const session=await requireSession();const tenants=await getPrisma().tenant.findMany({where:isSuperAdmin(session)?{}:{id:session.user.tenantId??"__none__"},include:tenantInclude,orderBy:{createdAt:"desc"}});return NextResponse.json({tenants:serializeTenant(tenants)})}catch(error){if(error instanceof Response)return NextResponse.json({message:error.statusText||"Acceso denegado"},{status:error.status});console.error("No se pudieron listar los tenants",error);return NextResponse.json({error:"DATABASE_UNAVAILABLE",message:"No fue posible consultar PostgreSQL."},{status:503})}}

type ProvisionBody={name?:string;slug?:string;status?:"ACTIVE"|"SUSPENDED"|"INACTIVE";planId?:string;branding?:Record<string,unknown>;verticalTemplateId?:string|null;moduleIds?:string[];crmFeatures?:Array<{featureId:string;active:boolean}>;maxUsers?:number;admin?:{name?:string;email?:string;jobTitle?:string;password?:string}};
export async function POST(request:Request){if(!isDatabaseConfigured())return unavailable();try{
  const session=await requireSession();if(!isSuperAdmin(session))throw new Response("Solo SUPER_ADMIN puede crear empresas",{status:403});const body=await request.json() as ProvisionBody;
  const name=body.name?.trim(),slug=slugify(body.slug||body.name||""),status=body.status??"ACTIVE",planId=body.planId,moduleIds=[...new Set(body.moduleIds??[])],maxUsers=Math.trunc(Number(body.maxUsers)),adminName=body.admin?.name?.trim(),adminEmail=body.admin?.email?.trim().toLowerCase(),adminPassword=body.admin?.password;
  if(!name||!slug||!planId||!adminName||!adminEmail||!adminPassword)return NextResponse.json({message:"Empresa, plan y administrador inicial son obligatorios."},{status:400});if(adminPassword.length<12)return NextResponse.json({message:"La contraseña temporal debe tener al menos 12 caracteres."},{status:400});if(!Number.isFinite(maxUsers)||maxUsers<1)return NextResponse.json({message:"El límite de usuarios debe ser mayor que cero."},{status:400});
  const passwordHash=await hash(adminPassword,12),prisma=getPrisma();const tenant=await prisma.$transaction(async tx=>{
    const [plan,allModules,template,maxDefinition,permissions]=await Promise.all([tx.plan.findFirst({where:{id:planId,status:"ACTIVE"}}),tx.module.findMany({where:{status:"ACTIVE"}}),body.verticalTemplateId?tx.verticalTemplate.findFirst({where:{id:body.verticalTemplateId,active:true},include:{features:true}}):null,tx.limitDefinition.findUnique({where:{code:"max-users"}}),tx.permission.findMany()]);
    if(!plan||!maxDefinition)throw new Error("Plan o definición de límite no disponible");if(moduleIds.some(id=>!allModules.some(module=>module.id===id)))throw new Error("Se recibió un módulo no válido");if(body.verticalTemplateId&&!template)throw new Error("Plantilla vertical no válida");const requestedFeatures=new Map((body.crmFeatures??[]).map(item=>[item.featureId,Boolean(item.active)]));if([...requestedFeatures.keys()].some(id=>!template?.features.some(feature=>feature.id===id)))throw new Error("Función CRM fuera de la plantilla seleccionada");
    const created=await tx.tenant.create({data:{name,slug,status,planId:plan.id,branding:{create:{displayName:String(body.branding?.displayName||name).trim(),logoUrl:optional(body.branding?.logoUrl),logoDarkUrl:optional(body.branding?.logoDarkUrl),faviconUrl:optional(body.branding?.faviconUrl),primaryColor:optional(body.branding?.primaryColor),secondaryColor:optional(body.branding?.secondaryColor),loginTitle:optional(body.branding?.loginTitle),loginSubtitle:optional(body.branding?.loginSubtitle),loginBackgroundUrl:optional(body.branding?.loginBackgroundUrl),subdomain:optional(body.branding?.subdomain)||slug,customDomain:optional(body.branding?.customDomain)}},modules:{create:allModules.map(module=>({moduleId:module.id,enabled:moduleIds.includes(module.id),activatedAt:moduleIds.includes(module.id)?new Date():null}))},limitOverrides:{create:{limitId:maxDefinition.id,value:BigInt(maxUsers)}},...(template?{verticalTemplates:{create:{verticalTemplateId:template.id,active:true}},crmFeatures:{create:template.features.map(feature=>({featureId:feature.id,active:requestedFeatures.get(feature.id)??feature.defaultActive}))}}:{})}});
    const permissionId=new Map(permissions.map(permission=>[permission.code,permission.id]));const roleSpecs=[{code:"COMPANY_ADMIN",name:"Administrador de empresa",permissions:["tenant.read","users.read","users.manage","modules.read"]},{code:"SUPERVISOR",name:"Supervisor",permissions:["tenant.read","users.read","reports.read"]},{code:"AGENT",name:"Agente",permissions:["tenant.read","operations.basic"]}];let companyAdminRoleId="";for(const spec of roleSpecs){const role=await tx.role.create({data:{code:spec.code,name:spec.name,tenantId:created.id,isSystem:true,permissions:{create:spec.permissions.map(code=>({permissionId:permissionId.get(code)!}))}}});if(spec.code==="COMPANY_ADMIN")companyAdminRoleId=role.id}
    await tx.user.create({data:{name:adminName,email:adminEmail,passwordHash,status:"ACTIVE",tenantId:created.id,roleId:companyAdminRoleId,jobTitle:optional(body.admin?.jobTitle)}});return tx.tenant.findUniqueOrThrow({where:{id:created.id},include:tenantInclude})
  });return NextResponse.json({tenant:serializeTenant(tenant)},{status:201});
 }catch(error){if(error instanceof Response)return NextResponse.json({message:(await error.text())||"Acceso denegado"},{status:error.status});console.error("No se pudo provisionar el tenant",error);return NextResponse.json({message:"No fue posible provisionar la empresa completa. No se guardaron cambios parciales."},{status:400})}}
