import "dotenv/config";
import * as XLSX from "xlsx";
import { getPrisma } from "../lib/prisma";
import { listOperationalCustomers } from "../lib/crm-operational-query";
import { matchExternalRow, type NormalizedExternalRow } from "../lib/reconciliation-engine";
import { buildReconciliationTemplate, reconciliationTemplateColumns, reconciliationTemplateFileName } from "../lib/reconciliation-template";

function check(value:unknown,message:string){if(!value)throw new Error(message);console.log(`✓ ${message}`)}
const prisma=getPrisma();
async function main(){const yc=await prisma.tenant.findUniqueOrThrow({where:{slug:"yc-telecomunicaciones"}}),clinic=await prisma.tenant.findUniqueOrThrow({where:{slug:"clinica-demo"}}),before={customers:await prisma.customer.count({where:{tenantId:yc.id}}),sales:await prisma.sale.count({where:{tenantId:yc.id}}),leads:await prisma.lead.count({where:{tenantId:yc.id}}),followUps:await prisma.followUp.count({where:{tenantId:yc.id}}),clinicCustomers:await prisma.customer.count({where:{tenantId:clinic.id}}),clinicSales:await prisma.sale.count({where:{tenantId:clinic.id}})};
  const customers=await listOperationalCustomers(yc.id,{page:1,pageSize:25});check(customers.total===731&&customers.summary.customers===731,"1. Clientes totales conserva los 731 Customer reales");check(customers.summary.sales===767,"2. Ventas registradas conserva las 767 Sale reales");check(customers.summary.approvedSales===await prisma.sale.count({where:{tenantId:yc.id,status:"APROBADA"}}),"3. Ventas aprobadas se calcula desde PostgreSQL");const now=new Date(),start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)),end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));check(customers.summary.monthSales===await prisma.sale.count({where:{tenantId:yc.id,saleDate:{gte:start,lt:end}}}),"4. Ventas del mes usa el mes actual y fechas reales");
  const template=buildReconciliationTemplate(),workbook=XLSX.read(template,{type:"buffer"});check(workbook.SheetNames.join("|")==="LIQUIDACION|INSTRUCCIONES","5. La plantilla contiene LIQUIDACION e INSTRUCCIONES");const headers=(XLSX.utils.sheet_to_json(workbook.Sheets.LIQUIDACION,{header:1})[0]??[]) as string[];check(JSON.stringify(headers)===JSON.stringify(reconciliationTemplateColumns),"6. La plantilla contiene las 13 columnas solicitadas");check(reconciliationTemplateFileName(yc.name)==="plantilla_conciliacion_yc.xlsx","7. El nombre del archivo es genérico por tenant");
  const base={tenantId:yc.id,sourceRecordKey:null,sec:null,sot:null,msisdn:"999111222",customerDocumentSnapshot:"12345678",saleDate:new Date("2026-01-15T00:00:00Z"),productNameSnapshot:"Móvil postpago",planNameSnapshot:"69.90"},candidates=[{...base,id:"sale-a"},{...base,id:"sale-b",msisdn:"999333444"}],row:NormalizedExternalRow={rowNumber:2,providerReference:null,sec:null,sot:null,phone:null,document:"12345678",customerName:null,saleDate:null,product:null,plan:null,recognizedAmount:null,rawData:{}};const ambiguous=matchExternalRow(row,candidates);check(ambiguous.sale===null&&ambiguous.matchStatus==="POSSIBLE_MATCH"&&ambiguous.matchedBy==="DNI_UNIQUE_SALE","8. DNI solo no fuerza un match cuando hay varias ventas");check(matchExternalRow(row,[candidates[0]]).sale?.id==="sale-a","9. DNI puede proponer la única venta inequívoca");
  const after={customers:await prisma.customer.count({where:{tenantId:yc.id}}),sales:await prisma.sale.count({where:{tenantId:yc.id}}),leads:await prisma.lead.count({where:{tenantId:yc.id}}),followUps:await prisma.followUp.count({where:{tenantId:yc.id}}),clinicCustomers:await prisma.customer.count({where:{tenantId:clinic.id}}),clinicSales:await prisma.sale.count({where:{tenantId:clinic.id}})};check(JSON.stringify(before)===JSON.stringify(after),"10. YC y Clínica Demo quedan intactos; no se crean ni eliminan datos");console.log(JSON.stringify({before,after,summary:customers.summary},null,2))}
main().finally(()=>prisma.$disconnect());

