import "dotenv/config";
import assert from "node:assert/strict";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const baseUrl=process.env.APP_URL??"http://localhost:3001",password=process.env.DEMO_PASSWORD;if(!process.env.DATABASE_URL||!password)throw new Error("Entorno incompleto");
const prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
async function login(email:string){const response=await fetch(`${baseUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});assert.equal(response.status,200);return response.headers.get("set-cookie")!.split(";")[0]}
async function main(){const createdUserIds:string[]=[];let productsFeatureId="";try{
  const [yc,clinic]=await Promise.all([prisma.tenant.findUniqueOrThrow({where:{slug:"yc-telecomunicaciones"}}),prisma.tenant.findUniqueOrThrow({where:{slug:"clinica-demo"}})]);
  const assignment=await prisma.tenantVerticalTemplate.findUniqueOrThrow({where:{tenantId_verticalTemplateId:{tenantId:yc.id,verticalTemplateId:(await prisma.verticalTemplate.findUniqueOrThrow({where:{code:"CRM_TELECOM"}})).id}},include:{verticalTemplate:{include:{features:{include:{tenantFeatures:{where:{tenantId:yc.id}}}}}}}});assert.equal(assignment.active,true);assert.equal(assignment.verticalTemplate.name,"CRM Ventas Telecom");assert.equal(await prisma.tenantVerticalTemplate.count({where:{tenantId:clinic.id}}),0);
  const activeCodes=assignment.verticalTemplate.features.filter(feature=>feature.tenantFeatures.some(item=>item.active)).map(feature=>feature.code).sort();const inactiveCodes=assignment.verticalTemplate.features.filter(feature=>!feature.tenantFeatures.some(item=>item.active)).map(feature=>feature.code).sort();assert.deepEqual(activeCodes,["commercial-plans","customers","follow-ups","leads","products","sales"]);assert.deepEqual(inactiveCodes,["advanced-dashboard","commissions","finance","reconciliation"]);
  const superCookie=await login("superadmin@mentorify.test"),ycCookie=await login("admin@yctelecom.test");const configuration=await fetch(`${baseUrl}/api/core/tenants/${yc.id}/vertical-template`,{headers:{cookie:superCookie}});assert.equal(configuration.status,200);const configBody=await configuration.json() as {maxUsers:number;activeUsers:number};assert.equal(configBody.maxUsers,7);assert.equal(configBody.activeUsers,4);assert.equal((await fetch(`${baseUrl}/api/core/tenants/${yc.id}/vertical-template`,{headers:{cookie:ycCookie}})).status,403);
  const metaResponse=await fetch(`${baseUrl}/api/crm/meta`,{headers:{cookie:ycCookie}});assert.equal(metaResponse.status,200);const meta=await metaResponse.json() as {activeFeatures:string[]};assert.deepEqual(meta.activeFeatures.sort(),activeCodes);assert.equal((await fetch(`${baseUrl}/api/crm/commissions`,{headers:{cookie:ycCookie}})).status,403);const inactivePage=await fetch(`${baseUrl}/crm/commissions`,{headers:{cookie:ycCookie},redirect:"manual"});assert.ok([307,308].includes(inactivePage.status));
  const productsFeature=assignment.verticalTemplate.features.find(feature=>feature.code==="products")!;productsFeatureId=productsFeature.id;const productsBefore=await prisma.product.count({where:{tenantId:yc.id}});const disable=await fetch(`${baseUrl}/api/core/tenants/${yc.id}/vertical-template`,{method:"PATCH",headers:{cookie:superCookie,"Content-Type":"application/json"},body:JSON.stringify({featureId:productsFeature.id,active:false})});assert.equal(disable.status,200);assert.equal((await fetch(`${baseUrl}/api/crm/products`,{headers:{cookie:ycCookie}})).status,403);assert.equal(await prisma.product.count({where:{tenantId:yc.id}}),productsBefore);const enable=await fetch(`${baseUrl}/api/core/tenants/${yc.id}/vertical-template`,{method:"PATCH",headers:{cookie:superCookie,"Content-Type":"application/json"},body:JSON.stringify({featureId:productsFeature.id,active:true})});assert.equal(enable.status,200);assert.equal(await prisma.product.count({where:{tenantId:yc.id}}),productsBefore);
  const maxDefinition=await prisma.limitDefinition.findUniqueOrThrow({where:{code:"max-users"}});const ycOverride=await prisma.tenantLimitOverride.findUniqueOrThrow({where:{tenantId_limitId:{tenantId:yc.id,limitId:maxDefinition.id}}});assert.equal(Number(ycOverride.value),7);const clinicOverride=await prisma.tenantLimitOverride.findUnique({where:{tenantId_limitId:{tenantId:clinic.id,limitId:maxDefinition.id}}});const businessLimit=await prisma.planLimit.findFirstOrThrow({where:{plan:{tenants:{some:{id:clinic.id}}},limitId:maxDefinition.id}});assert.equal(Number(clinicOverride?.value??businessLimit.value),25);
  const agentRole=await prisma.role.findFirstOrThrow({where:{tenantId:yc.id,code:"AGENT"}});const stamp=Date.now();for(let index=1;index<=3;index++){const response=await fetch(`${baseUrl}/api/users`,{method:"POST",headers:{cookie:ycCookie,"Content-Type":"application/json"},body:JSON.stringify({name:`Usuario Límite ${index}`,email:`yc-limit-${stamp}-${index}@qa.test`,password:"Temporary-QA-2026!",roleId:agentRole.id})});assert.equal(response.status,201);createdUserIds.push(((await response.json()) as {user:{id:string}}).user.id)}assert.equal(await prisma.user.count({where:{tenantId:yc.id,status:"ACTIVE"}}),7);const eighth=await fetch(`${baseUrl}/api/users`,{method:"POST",headers:{cookie:ycCookie,"Content-Type":"application/json"},body:JSON.stringify({name:"Octavo usuario",email:`yc-limit-${stamp}-8@qa.test`,password:"Temporary-QA-2026!",roleId:agentRole.id})});assert.equal(eighth.status,409);assert.equal(((await eighth.json()) as {message:string}).message,"Has alcanzado el límite de usuarios configurado para tu empresa.");
  console.log(JSON.stringify({template:"CRM_TELECOM",ycAssigned:true,clinicUnassigned:true,activeFeatures:activeCodes,inactiveFeatures:inactiveCodes,superAdminConfigurationAccess:true,companyAdminConfigurationDenied:true,inactiveFeatureHidden:true,directInactiveFeatureDenied:true,featureTogglePreservesData:true,maxUsers:7,activeUsersBeforeTest:4,availableSlotsBeforeTest:3,eighthUserBlocked:true,clinicEffectiveLimit:25},null,2));
 }finally{if(productsFeatureId){const yc=await prisma.tenant.findUnique({where:{slug:"yc-telecomunicaciones"}});if(yc)await prisma.tenantCrmFeature.updateMany({where:{tenantId:yc.id,featureId:productsFeatureId},data:{active:true}})}if(createdUserIds.length)await prisma.user.deleteMany({where:{id:{in:createdUserIds}}});await prisma.$disconnect()}}
main().catch(error=>{console.error(error);process.exitCode=1});
