import "dotenv/config";
import assert from "node:assert/strict";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const baseUrl=process.env.APP_URL??"http://localhost:3001",demoPassword=process.env.DEMO_PASSWORD;if(!process.env.DATABASE_URL||!demoPassword)throw new Error("Entorno incompleto");const prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
async function login(email:string,password=demoPassword,tenantSlug?:string){const response=await fetch(`${baseUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,tenantSlug})});return{response,cookie:response.headers.get("set-cookie")?.split(";")[0]??""}}
async function main(){let qaTenantId:string|undefined;const stamp=Date.now(),slug=`empresa-qa-temporal-${stamp}`,adminEmail=`admin-${stamp}@empresa-qa.test`,password="Temporary-QA-2026!";try{
  const superLogin=await login("superadmin@mentorify.test");assert.equal(superLogin.response.status,200);const optionsResponse=await fetch(`${baseUrl}/api/core/provisioning-options`,{headers:{cookie:superLogin.cookie}});assert.equal(optionsResponse.status,200);const options=await optionsResponse.json() as {plans:Array<{id:string;code:string}>;modules:Array<{id:string;code:string}>;templates:Array<{id:string;code:string;features:Array<{id:string;code:string;defaultActive:boolean}>}>};const plan=options.plans.find(item=>item.code==="business")!,template=options.templates.find(item=>item.code==="CRM_TELECOM")!,crmModule=options.modules.find(item=>item.code==="crm")!,reportsModule=options.modules.find(item=>item.code==="reportes")!;
  const body={name:"Empresa QA Temporal",slug,status:"ACTIVE",planId:plan.id,branding:{displayName:"QA Telecom",primaryColor:"#3456aa",secondaryColor:"#18213d",loginTitle:"Acceso QA",loginSubtitle:"Entorno temporal",subdomain:slug},verticalTemplateId:template.id,moduleIds:[crmModule.id,reportsModule.id],crmFeatures:template.features.map(feature=>({featureId:feature.id,active:["leads","customers","sales","products"].includes(feature.code)})),maxUsers:2,admin:{name:"Administradora QA",email:adminEmail,jobTitle:"Gerente",password}};
  const create=await fetch(`${baseUrl}/api/core/tenants`,{method:"POST",headers:{cookie:superLogin.cookie,"Content-Type":"application/json"},body:JSON.stringify(body)}),createText=await create.text();assert.equal(create.status,201,createText);qaTenantId=(JSON.parse(createText) as {tenant:{id:string}}).tenant.id;
  const tenant=await prisma.tenant.findUniqueOrThrow({where:{id:qaTenantId},include:{branding:true,plan:true,modules:{include:{module:true}},limitOverrides:{include:{definition:true}},verticalTemplates:{include:{verticalTemplate:true}},crmFeatures:{include:{feature:true}},users:{include:{role:true}}}});assert.equal(tenant.branding?.displayName,"QA Telecom");assert.equal(tenant.plan.code,"business");assert.deepEqual(tenant.modules.filter(item=>item.enabled).map(item=>item.module.code).sort(),["crm","reportes"]);assert.equal(tenant.verticalTemplates[0]?.verticalTemplate.code,"CRM_TELECOM");assert.deepEqual(tenant.crmFeatures.filter(item=>item.active).map(item=>item.feature.code).sort(),["customers","leads","products","sales"]);assert.equal(Number(tenant.limitOverrides.find(item=>item.definition.code==="max-users")?.value),2);assert.equal(tenant.users.length,1);assert.equal(tenant.users[0].role.code,"COMPANY_ADMIN");assert.equal(tenant.users[0].jobTitle,"Gerente");
  const adminLogin=await login(adminEmail,password,slug);assert.equal(adminLogin.response.status,200);assert.equal(((await adminLogin.response.json()) as {session:{user:{tenantId:string}}}).session.user.tenantId,qaTenantId);const yc=await prisma.tenant.findUniqueOrThrow({where:{slug:"yc-telecomunicaciones"}});assert.equal((await fetch(`${baseUrl}/api/users?tenantId=${yc.id}`,{headers:{cookie:adminLogin.cookie}})).status,403);const callCenter=await fetch(`${baseUrl}/call-center`,{headers:{cookie:adminLogin.cookie},redirect:"manual"});assert.ok([307,308].includes(callCenter.status));
  const agentRole=await prisma.role.findFirstOrThrow({where:{tenantId:qaTenantId,code:"AGENT"}});const second=await fetch(`${baseUrl}/api/users`,{method:"POST",headers:{cookie:adminLogin.cookie,"Content-Type":"application/json"},body:JSON.stringify({name:"Segundo usuario QA",email:`second-${stamp}@qa.test`,jobTitle:"Asistente",password,roleId:agentRole.id})});assert.equal(second.status,201);const third=await fetch(`${baseUrl}/api/users`,{method:"POST",headers:{cookie:adminLogin.cookie,"Content-Type":"application/json"},body:JSON.stringify({name:"Tercer usuario QA",email:`third-${stamp}@qa.test`,password,roleId:agentRole.id})});assert.equal(third.status,409);
  const edit=await fetch(`${baseUrl}/api/core/tenants/${qaTenantId}`,{method:"PATCH",headers:{cookie:superLogin.cookie,"Content-Type":"application/json"},body:JSON.stringify({name:"Empresa QA Temporal Editada",status:"SUSPENDED"})});assert.equal(edit.status,200);assert.equal((await prisma.tenant.findUniqueOrThrow({where:{id:qaTenantId}})).status,"SUSPENDED");await prisma.tenant.update({where:{id:qaTenantId},data:{status:"ACTIVE"}});
  const failedSlug=`qa-rollback-${stamp}`;const failed=await fetch(`${baseUrl}/api/core/tenants`,{method:"POST",headers:{cookie:superLogin.cookie,"Content-Type":"application/json"},body:JSON.stringify({...body,slug:failedSlug,branding:{...body.branding,subdomain:failedSlug},admin:{...body.admin,email:"admin@yctelecom.test"}})});assert.equal(failed.status,400);assert.equal(await prisma.tenant.count({where:{slug:failedSlug}}),0);
  console.log(JSON.stringify({tenantCreated:true,brandingCreated:true,planAssigned:true,limitAssigned:true,templateAssigned:true,modulesAssigned:true,crmFeaturesAssigned:true,initialCompanyAdminCreated:true,jobTitleSeparatedFromRole:true,companyAdminLogin:true,tenantIsolation:true,inactiveModuleBlocked:true,userLimitEnforced:true,existingTenantEditing:true,transactionRollbackLeavesNoTenant:true,qaCleanup:"pending-finally"},null,2));
 }finally{if(qaTenantId)await prisma.tenant.deleteMany({where:{id:qaTenantId}});assert.equal(await prisma.tenant.count({where:{slug}}),0);await prisma.$disconnect()}}
main().catch(error=>{console.error(error);process.exitCode=1});
