import "dotenv/config";import assert from "node:assert/strict";import {PrismaPg} from "@prisma/adapter-pg";import {PrismaClient} from "@prisma/client";
const baseUrl=process.env.APP_URL??"http://localhost:3001",password=process.env.DEMO_PASSWORD;if(!process.env.DATABASE_URL||!password)throw new Error("Entorno incompleto");const prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
function absorb(cookie:string,response:Response){const values=typeof response.headers.getSetCookie==="function"?response.headers.getSetCookie():[response.headers.get("set-cookie")??""];const jar=new Map(cookie.split("; ").filter(Boolean).map(part=>{const index=part.indexOf("=");return[part.slice(0,index),part.slice(index+1)]}));for(const value of values){const part=value.split(";")[0],index=part.indexOf("=");if(index>0){const key=part.slice(0,index),val=part.slice(index+1);if(val)jar.set(key,val);else jar.delete(key)}}return[...jar].map(([key,val])=>`${key}=${val}`).join("; ")}
async function login(email:string){const response=await fetch(`${baseUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});assert.equal(response.status,200);return absorb("",response)}async function setContext(cookie:string,tenantId:string|null){const response=await fetch(`${baseUrl}/api/auth/tenant-context`,{method:"POST",headers:{cookie,"Content-Type":"application/json"},body:JSON.stringify({tenantId})});return{response,cookie:absorb(cookie,response)}}
async function main(){let tenantBId:string|undefined;try{const clinic=await prisma.tenant.findUniqueOrThrow({where:{slug:"clinica-demo"}}),plan=await prisma.plan.findUniqueOrThrow({where:{code:"business"}}),crm=await prisma.module.findUniqueOrThrow({where:{code:"crm"}});let superCookie=await login("superadmin@mentorify.test");({cookie:superCookie}=await setContext(superCookie,null));const noContextApi=await fetch(`${baseUrl}/api/crm/leads`,{headers:{cookie:superCookie}});assert.equal(noContextApi.status,400);assert.equal((await noContextApi.json() as {message:string}).message,"Selecciona una empresa para acceder al CRM.");const noContextPage=await fetch(`${baseUrl}/crm/leads`,{headers:{cookie:superCookie}});assert.equal(noContextPage.status,200);assert.ok((await noContextPage.text()).includes("Selecciona una empresa para acceder al CRM."));
 const clinicSelection=await setContext(superCookie,clinic.id);assert.equal(clinicSelection.response.status,200);superCookie=clinicSelection.cookie;const clinicCrm=await fetch(`${baseUrl}/api/crm/leads`,{headers:{cookie:superCookie}});assert.equal(clinicCrm.status,200);const clinicItems=(await clinicCrm.json() as {items:Array<{tenantId:string}>}).items;assert.ok(clinicItems.length>0&&clinicItems.every(item=>item.tenantId===clinic.id));const crmIndex=await fetch(`${baseUrl}/crm`,{headers:{cookie:superCookie},redirect:"manual"});assert.ok([307,308].includes(crmIndex.status));assert.equal(new URL(crmIndex.headers.get("location")!,baseUrl).pathname,"/crm/leads");
 const tenantB=await prisma.tenant.create({data:{name:"Empresa B Admin Context QA",slug:`admin-context-${Date.now()}`,planId:plan.id,modules:{create:{moduleId:crm.id,enabled:true}}}});tenantBId=tenantB.id;const switchResult=await setContext(superCookie,tenantB.id);assert.equal(switchResult.response.status,200);superCookie=switchResult.cookie;const tenantBCrm=await fetch(`${baseUrl}/api/crm/leads`,{headers:{cookie:superCookie}});assert.equal(tenantBCrm.status,200);assert.equal((await tenantBCrm.json() as {items:unknown[]}).items.length,0);
 for(const email of ["admin@clinicademo.test","supervisor@clinicademo.test","agente@clinicademo.test"]){const cookie=await login(email);assert.equal((await setContext(cookie,tenantB.id)).response.status,403,`${email} cambió de tenant`)}const invalid=await setContext(superCookie,"tenant-inexistente");assert.equal(invalid.response.status,404);console.log(JSON.stringify({superAdminClinicCrm:true,superAdminTenantSwitch:true,companyAdminCannotSwitch:true,supervisorCannotSwitch:true,agentCannotSwitch:true,invalidTenantRejected:true,noTenantMessage:true,crmIndexWorks:true},null,2));
 }finally{if(tenantBId)await prisma.tenant.delete({where:{id:tenantBId}});await prisma.$disconnect()}}
main().catch(error=>{console.error(error);process.exitCode=1});
