import "dotenv/config";import assert from "node:assert/strict";import {PrismaPg} from "@prisma/adapter-pg";import {PrismaClient} from "@prisma/client";
const baseUrl=process.env.APP_URL??"http://localhost:3001",password=process.env.DEMO_PASSWORD;if(!process.env.DATABASE_URL||!password)throw new Error("Entorno incompleto");const prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
async function login(email:string){const response=await fetch(`${baseUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});assert.equal(response.status,200);const cookie=response.headers.get("set-cookie")?.split(";")[0];assert.ok(cookie);return cookie}async function call(path:string,cookie:string,method="GET",body?:object){return fetch(`${baseUrl}${path}`,{method,headers:{cookie,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined})}
async function main(){let tenantBId:string|undefined,qaLeadId:string|undefined,qaSaleId:string|undefined;try{
 const clinic=await prisma.tenant.findUniqueOrThrow({where:{slug:"clinica-demo"}}),saasPlan=await prisma.plan.findUniqueOrThrow({where:{code:"business"}}),crm=await prisma.module.findUniqueOrThrow({where:{code:"crm"}}),sourceAgent=await prisma.user.findUniqueOrThrow({where:{email:"agente@clinicademo.test"}}),secondAgent=await prisma.user.findUniqueOrThrow({where:{email:"promotor2@clinicademo.test"}}),supervisor=await prisma.user.findUniqueOrThrow({where:{email:"supervisor@clinicademo.test"}});
 const tenantB=await prisma.tenant.create({data:{name:"Empresa B Sales QA",slug:`empresa-b-sales-${Date.now()}`,planId:saasPlan.id,modules:{create:{moduleId:crm.id,enabled:true}}}});tenantBId=tenantB.id;const roleSupB=await prisma.role.create({data:{tenantId:tenantB.id,code:"SUPERVISOR",name:"Supervisor B"}}),roleAgentB=await prisma.role.create({data:{tenantId:tenantB.id,code:"AGENT",name:"Agente B"}});const supB=await prisma.user.create({data:{tenantId:tenantB.id,roleId:roleSupB.id,name:"Supervisor B",email:`sup-b-${Date.now()}@qa.test`,passwordHash:sourceAgent.passwordHash}}),agentB=await prisma.user.create({data:{tenantId:tenantB.id,roleId:roleAgentB.id,supervisorId:supB.id,name:"Agente B",email:`agent-b-sale-${Date.now()}@qa.test`,passwordHash:sourceAgent.passwordHash}});const stageB=await prisma.pipelineStage.create({data:{tenantId:tenantB.id,name:"Venta registrada",code:"VENTA_REGISTRADA",order:1}});const leadB=await prisma.lead.create({data:{tenantId:tenantB.id,name:"Lead B",phone:"900000001",origin:"QA",pipelineStageId:stageB.id,assignedUserId:agentB.id}}),customerB=await prisma.customer.create({data:{tenantId:tenantB.id,name:"Cliente B",phone:"900000002",ownerUserId:agentB.id}}),productB=await prisma.product.create({data:{tenantId:tenantB.id,name:"Producto B",code:"PROD-B",category:"QA"}}),planB=await prisma.commercialPlan.create({data:{tenantId:tenantB.id,productId:productB.id,name:"Plan B",code:"PLAN-B"}});const saleB=await prisma.sale.create({data:{tenantId:tenantB.id,leadId:leadB.id,customerId:customerB.id,productId:productB.id,commercialPlanId:planB.id,agentId:agentB.id,supervisorId:supB.id,transactionType:"OTRO",customerNameSnapshot:customerB.name,productNameSnapshot:productB.name,planNameSnapshot:planB.name,createdByUserId:agentB.id,statusHistory:{create:{tenantId:tenantB.id,newStatus:"REGISTRADA",changedByUserId:agentB.id}}}});
 const admin=await login("admin@clinicademo.test"),agent=await login("agente@clinicademo.test"),sup=await login("supervisor@clinicademo.test");const adminSales=await(await call("/api/crm/sales",admin)).json() as {items:Array<{id:string}>};assert.ok(!adminSales.items.some(item=>item.id===saleB.id));assert.equal((await call(`/api/crm/sales/${saleB.id}`,admin)).status,403);
 const customerA=await prisma.customer.findFirstOrThrow({where:{tenantId:clinic.id,ownerUserId:sourceAgent.id}}),productA=await prisma.product.findFirstOrThrow({where:{tenantId:clinic.id,code:"FIBRA"}}),planA=await prisma.commercialPlan.findFirstOrThrow({where:{tenantId:clinic.id,code:"FIBRA-500"}}),mismatchedPlan=await prisma.commercialPlan.findFirstOrThrow({where:{tenantId:clinic.id,code:"MOVIL-ILIMITADO"}});const basic={transactionType:"OTRO",agentId:sourceAgent.id,customerId:customerA.id,productId:productA.id};
 assert.equal((await call("/api/crm/sales",admin,"POST",{...basic,customerId:customerB.id})).status,403);assert.equal((await call("/api/crm/sales",admin,"POST",{...basic,productId:productB.id})).status,403);assert.equal((await call("/api/crm/sales",admin,"POST",{...basic,commercialPlanId:planB.id})).status,403);assert.equal((await call("/api/crm/sales",admin,"POST",{...basic,commercialPlanId:mismatchedPlan.id})).status,400);
 const agentSales=await(await call("/api/crm/sales",agent)).json() as {items:Array<{agentId:string}>};assert.ok(agentSales.items.every(item=>item.agentId===sourceAgent.id));const supervisorSales=await(await call("/api/crm/sales",sup)).json() as {items:Array<{agentId:string;id:string}>};assert.ok(supervisorSales.items.some(item=>item.agentId===sourceAgent.id)&&supervisorSales.items.some(item=>item.agentId===secondAgent.id));assert.ok(!supervisorSales.items.some(item=>item.id===saleB.id));
 const newStage=await prisma.pipelineStage.findUniqueOrThrow({where:{tenantId_code:{tenantId:clinic.id,code:"NUEVO"}}});const qaLead=await prisma.lead.create({data:{tenantId:clinic.id,name:"Lead Venta QA",phone:"955000001",origin:"QA",pipelineStageId:newStage.id,assignedUserId:sourceAgent.id,supervisorId:supervisor.id}});qaLeadId=qaLead.id;const createResponse=await call("/api/crm/sales",admin,"POST",{...basic,leadId:qaLead.id,commercialPlanId:planA.id,supervisorId:supB.id,sec:"QA-SEC",saleDate:new Date().toISOString()});assert.equal(createResponse.status,201);const created=(await createResponse.json() as {item:{id:string;supervisorId:string}}).item;qaSaleId=created.id;assert.equal(created.supervisorId,supervisor.id,"No se derivó supervisor del agente");assert.equal(await prisma.saleStatusHistory.count({where:{saleId:created.id,newStatus:"REGISTRADA"}}),1);assert.equal((await prisma.lead.findUniqueOrThrow({where:{id:qaLead.id},include:{pipelineStage:true}})).pipelineStage.code,"VENTA_REGISTRADA");assert.ok(await prisma.leadStageHistory.count({where:{leadId:qaLead.id,pipelineStage:{code:"VENTA_REGISTRADA"}}}));
 const activate=await call(`/api/crm/sales/${created.id}`,admin,"PATCH",{status:"ACTIVADA",reason:"QA activación"});assert.equal(activate.status,200);assert.equal(await prisma.saleStatusHistory.count({where:{saleId:created.id,newStatus:"ACTIVADA"}}),1);assert.equal((await prisma.lead.findUniqueOrThrow({where:{id:qaLead.id},include:{pipelineStage:true}})).pipelineStage.code,"ACTIVADA");
 console.log(JSON.stringify({saleTenantIsolation:true,crossTenantCustomerDenied:true,crossTenantProductDenied:true,crossTenantPlanDenied:true,planProductMatchEnforced:true,agentSaleScope:true,supervisorTeamScope:true,leadSaleTransaction:true,activationPipelineSync:true,crossTenantSupervisorIgnored:true},null,2));
}finally{if(qaSaleId)await prisma.sale.deleteMany({where:{id:qaSaleId}});if(qaLeadId)await prisma.lead.deleteMany({where:{id:qaLeadId}});if(tenantBId)await prisma.tenant.delete({where:{id:tenantBId}});await prisma.$disconnect()}}
main().catch(error=>{console.error(error);process.exitCode=1});
