import "dotenv/config";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { getPrisma } from "../lib/prisma";
import { listOperationalCustomers } from "../lib/crm-operational-query";

function check(value:unknown,message:string){if(!value)throw new Error(message);console.log(`✓ ${message}`)}
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex"),prisma=getPrisma();
async function main(){const yc=await prisma.tenant.findUniqueOrThrow({where:{slug:"yc-telecomunicaciones"}}),clinic=await prisma.tenant.findUniqueOrThrow({where:{slug:"clinica-demo"}}),sales=await prisma.sale.findMany({where:{tenantId:yc.id},select:{id:true,status:true},orderBy:{id:"asc"}}),customers=await prisma.customer.findMany({where:{tenantId:yc.id},select:{id:true,ownerUserId:true},orderBy:{id:"asc"}}),page=await listOperationalCustomers(yc.id,{page:1,pageSize:25}),source=await readFile(new URL("../components/crm-operational-workspace.tsx",import.meta.url),"utf8");
  check(customers.length===731&&page.summary.customers===731,"1. Customer YC permanece en 731");check(sales.length===767&&page.summary.sales===767,"2. Sale YC permanece en 767");check(await prisma.lead.count({where:{tenantId:yc.id}})===0&&await prisma.followUp.count({where:{tenantId:yc.id}})===0,"3. No se crearon Leads ni FollowUps");check(hash(sales)==="4cfae711c54130b469b9660f7d2ba9d2c0eae02eb7281ddf730eb25ef8504a9c","4. Los estados históricos de Sale no cambiaron");check(hash(customers)==="b8ad7fc632e828c82f94f61f98b40a48bfee7045319d08e549556e7ac004d21b","5. Los responsables de Customer no cambiaron");check(source.includes("<th>DNI</th><th>Cliente</th><th>Teléfono</th><th>Ventas</th><th>Última venta</th><th>Último producto / plan</th><th>Estado</th><th>Acción</th>"),"6. La tabla usa el orden visual solicitado");check(!source.match(/<th>Responsable<\/th>/),"7. Responsable no aparece en la tabla principal");check(source.includes('item.lastSale?<strong>{date(item.lastSale.saleDate)}</strong>:"—"'),"8. Última venta muestra únicamente la fecha");check(source.includes('item.lastSale?<Status value={item.lastSale.status}/>:"—"'),"9. Estado proviene de la venta más reciente");check(source.includes('["Responsable actual",item.ownerUser?.name]'),"10. Responsable continúa disponible en Ver ficha");check(page.summary.approvedSales===767&&Number.isInteger(page.summary.monthSales),"11. Los cuatro KPI continúan calculados desde PostgreSQL");check(await prisma.customer.count({where:{tenantId:clinic.id}})===2&&await prisma.sale.count({where:{tenantId:clinic.id}})===3,"12. Clínica Demo permanece intacta");console.log(JSON.stringify({customers:customers.length,sales:sales.length,approvedSales:page.summary.approvedSales,monthSales:page.summary.monthSales,statusHash:hash(sales),ownerHash:hash(customers)},null,2))}
main().finally(()=>prisma.$disconnect());

